import type { Candidate } from '../src/features/sound/domain/bank.ts';

// SHORTLIST.md is written from this by `pnpm sounds:fetch`. Best first in each slot.
export const SHORTLIST: readonly Candidate[] = [
  {
    slot: 'music-menu',
    title: 'Seaside Village',
    page: 'https://opengameart.org/content/seaside-village',
    preview: 'https://opengameart.org/sites/default/files/Sea%20side%20Village.flac',
    fetch: 'https://opengameart.org/sites/default/files/Sea%20side%20Village.flac',
    author: 'KarateStudios',
    licence: 'CC0',
    seconds: 76,
    why: 'a village in the sun by the ocean; tagged relaxing, island, sunny; even level, short enough to loop whole',
    cut: { start: 0, length: 75 },
  },
  {
    slot: 'music-menu',
    title: 'Quaint Town (Loopable)',
    page: 'https://opengameart.org/content/quaint-town',
    preview: 'https://opengameart.org/sites/default/files/Quaint%20Town%20-%20LOOPABLE.mp3',
    fetch: 'https://opengameart.org/sites/default/files/Quaint%20Town%20-%20LOOPABLE.mp3',
    author: 'neonarkade',
    licence: 'CC0',
    seconds: 103,
    why: 'peaceful, happy town theme with a loopable edit',
    cut: { start: 0, length: 102 },
  },
  {
    slot: 'music-menu',
    title: 'Bossa Town',
    page: 'https://opengameart.org/content/bossa-town',
    preview: 'https://opengameart.org/sites/default/files/Bossa%20Town.wav_2.flac',
    fetch: 'https://opengameart.org/sites/default/files/Bossa%20Town.wav_2.flac',
    author: 'KarateStudios',
    licence: 'CC0',
    seconds: 100,
    why: 'cosy bossa nova beach-town theme; the page asks for credit (not binding under CC0)',
    cut: { start: 0, length: 100 },
  },
  {
    slot: 'music-menu',
    title: 'Good Morning',
    page: 'https://opengameart.org/content/good-morning',
    preview: 'https://opengameart.org/sites/default/files/Cakeflaps%20-%20Good%20Morning_0.ogg',
    fetch: 'https://opengameart.org/sites/default/files/Cakeflaps%20-%20Good%20Morning_0.ogg',
    author: "Cakeflaps (You're Perfect Studio)",
    licence: 'CC0',
    seconds: 121,
    why: 'gentle, loopable wake-up song',
    cut: { start: 0, length: 120 },
  },
  {
    slot: 'music-day',
    title: 'Feel Good Island',
    page: 'https://opengameart.org/content/feel-good-island',
    preview: 'https://opengameart.org/sites/default/files/island_0.ogg',
    fetch: 'https://opengameart.org/sites/default/files/island_0.ogg',
    author: 'HaelDB (Brandon Morris)',
    licence: 'CC0',
    seconds: 113,
    why: 'marimba, piano and light drums, island theme; cut before the fade-out',
    cut: { start: 0, length: 105 },
  },
  {
    slot: 'music-day',
    title: 'Vintage Hawaii',
    page: 'https://opengameart.org/content/vintage-hawaii',
    preview: 'https://opengameart.org/sites/default/files/vintage_hawaii.mp3',
    fetch: 'https://opengameart.org/sites/default/files/vintage_hawaii.mp3',
    author: 'Tarush Singhal',
    licence: 'CC0',
    seconds: 113,
    why: 'lo-fi summer beach track with ukulele and guitar, even level',
    cut: { start: 0, length: 113 },
  },
  {
    slot: 'music-day',
    title: 'Champ de tournesol',
    page: 'https://opengameart.org/content/champ-de-tournesol',
    preview: 'https://opengameart.org/sites/default/files/Komiku_-_03_-_Champ_de_tournesol_0.mp3',
    fetch: 'https://opengameart.org/sites/default/files/Komiku_-_03_-_Champ_de_tournesol_0.mp3',
    author: 'Komiku (Loyalty Freak Music)',
    licence: 'CC0',
    seconds: 118,
    why: 'breezy light acoustic guitars with slide; contrasts with the marimba and ukulele',
    cut: { start: 0, length: 112 },
  },
  {
    slot: 'music-day',
    title: 'Blue Skies',
    page: 'https://opengameart.org/content/happy-lo-fi-lofi-collection',
    preview: '',
    fetch: 'https://opengameart.org/sites/default/files/happy_lo-fi_lofi_collection.zip',
    member: 'Happy Lo-Fi (Lofi Collection)/03 HoliznaCC0 - Blue Skies.mp3.mp3',
    author: 'Holizna',
    licence: 'CC0',
    seconds: 176,
    why: 'happy, relaxed lo-fi beat; inside an 82 MB zip',
    cut: { start: 10, length: 120 },
  },
  {
    slot: 'music-day',
    title: 'Happy Ukelele Island Surfing Theme',
    page: 'https://opengameart.org/content/happy-ukelele-island-surfing-theme',
    preview: 'https://opengameart.org/sites/default/files/ukele.mp3',
    fetch: 'https://opengameart.org/sites/default/files/ukele.mp3',
    author: 'Tarush Singhal',
    licence: 'CC0',
    seconds: 136,
    why: 'ukulele with 8-bit drums, summer and island; maybe perkier than relaxed',
    cut: { start: 0, length: 120 },
  },
  {
    slot: 'music-day',
    title: 'Bossa Shop Theme (HD)',
    page: 'https://opengameart.org/content/bossa-shop-theme-in-low-fi-and-hd',
    preview: 'https://opengameart.org/sites/default/files/springyspringo_-_bossa_hd_0.mp3',
    fetch: 'https://opengameart.org/sites/default/files/springyspringo_-_bossa_hd_0.mp3',
    author: 'SpringySpringo',
    licence: 'CC0',
    seconds: 87,
    why: 'mellow bossa nova shop loop, easy-listening café feel',
    cut: { start: 0, length: 86 },
  },
  {
    slot: 'music-night',
    title: 'Blue Moon Beach (alternate, no crackle)',
    page: 'https://opengameart.org/content/blue-moon-beach',
    preview: 'https://opengameart.org/sites/default/files/blue_moon_beach_alternate_0.ogg',
    fetch: 'https://opengameart.org/sites/default/files/blue_moon_beach_alternate_0.ogg',
    author: 'Tsorthan Grove',
    licence: 'CC0',
    seconds: 173,
    why: 'sparse, quiet ambient beach at night; skips the 20 s fade-in',
    cut: { start: 20, length: 120 },
  },
  {
    slot: 'music-night',
    title: 'Blue Moon Beach (original, with crackle)',
    page: 'https://opengameart.org/content/blue-moon-beach',
    preview: 'https://opengameart.org/sites/default/files/blue_moon_beach_0.ogg',
    fetch: 'https://opengameart.org/sites/default/files/blue_moon_beach_0.ogg',
    author: 'Tsorthan Grove',
    licence: 'CC0',
    seconds: 170,
    why: 'the same with a constant vinyl crackle',
    cut: { start: 15, length: 120 },
  },
  {
    slot: 'music-night',
    title: 'Contemplation',
    page: 'https://opengameart.org/content/contemplation-0',
    preview: 'https://opengameart.org/sites/default/files/Contemplation.mp3',
    fetch: 'https://opengameart.org/sites/default/files/Contemplation.mp3',
    author: 'Joth',
    licence: 'CC0',
    seconds: 120,
    why: 'pure quiet ambience without melody, slightly melancholy',
    cut: { start: 0, length: 120 },
  },
  {
    slot: 'music-night',
    title: 'Calm Ambient 3 (Lifewave 2k)',
    page: 'https://opengameart.org/content/calm-ambient-3-lifewave-2k',
    preview: 'https://opengameart.org/sites/default/files/006_lifeWave2k_0.mp3',
    fetch: 'https://opengameart.org/sites/default/files/006_lifeWave2k_0.mp3',
    author: 'cynicmusic (The Cynic Project)',
    licence: 'CC0',
    seconds: 187,
    why: 'relaxing pads with soft piano; the page shows an attribution note (not binding under CC0)',
    cut: { start: 5, length: 120 },
  },
  {
    slot: 'gulls',
    title: 'Seagulls screeching on the beach, on the peruvian shore.',
    page: 'https://freesound.org/people/felix.blume/sounds/155747/',
    preview: 'https://cdn.freesound.org/previews/155/155747_1661766-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/155/155747_1661766-hq.mp3',
    author: 'felix.blume',
    licence: 'CC0',
    seconds: 121.0,
    rating: 4.6,
    ratings: 38,
    why: 'Seagulls screeching on a Peruvian beach with ocean waves behind; most-rated gull bed, steady level',
    cut: { start: 33, length: 25 },
  },
  {
    slot: 'gulls',
    title: 'Gulls on The isles of Scilly',
    page: 'https://freesound.org/people/plantmonkey/sounds/377107/',
    preview: 'https://cdn.freesound.org/previews/377/377107_182472-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/377/377107_182472-hq.mp3',
    author: 'plantmonkey',
    licence: 'CC0',
    seconds: 98.2,
    rating: 4.9,
    ratings: 32,
    why: 'Gull colony with faint Atlantic surf, very well rated; quiet recording so needs gain',
    cut: { start: 33.5, length: 25 },
  },
  {
    slot: 'gulls',
    title: 'GullsChatter.wav',
    page: 'https://freesound.org/people/LouisDirector/sounds/331685/',
    preview: 'https://cdn.freesound.org/previews/331/331685_5827449-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/331/331685_5827449-hq.mp3',
    author: 'LouisDirector',
    licence: 'CC0',
    seconds: 28.0,
    rating: 4.9,
    ratings: 11,
    why: 'Dry close gull chatter at Brighton Beach NY, no surf; good to layer over a separate waves bed',
    cut: { start: 0, length: 28 },
  },
  {
    slot: 'birds',
    title: 'Jungle, Tropical birds and insects',
    page: 'https://freesound.org/people/myrinvp/sounds/423711/',
    preview: 'https://cdn.freesound.org/previews/423/423711_1451873-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/423/423711_1451873-hq.mp3',
    author: 'myrinvp',
    licence: 'CC0',
    seconds: 40.0,
    rating: 4.7,
    ratings: 77,
    why: 'Warm tropical birds and insects bed, most-rated option; constructed, not a real jungle',
    cut: { start: 11, length: 25 },
  },
  {
    slot: 'birds',
    title: 'Birds near a jungle stream (with Montezuma oropendola)',
    page: 'https://freesound.org/people/zachrau/sounds/812934/',
    preview: 'https://cdn.freesound.org/previews/812/812934_676927-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/812/812934_676927-hq.mp3',
    author: 'zachrau',
    licence: 'CC0',
    seconds: 73.8,
    rating: 4.6,
    ratings: 9,
    why: 'Real Costa Rica jungle birds with a soft stream and wind; cut avoids the oropendola call at 0:43',
    cut: { start: 3, length: 25 },
  },
  {
    slot: 'birds',
    title: 'Tuscan Birdsong.wav',
    page: 'https://freesound.org/people/gazsound/sounds/156002/',
    preview: 'https://cdn.freesound.org/previews/156/156002_412071-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/156/156002_412071-hq.mp3',
    author: 'gazsound',
    licence: 'CC0',
    seconds: 243.3,
    rating: 4.9,
    ratings: 9,
    why: 'Tuscan hillside morning birdsong, Mediterranean feel; sparse, individual calls',
    cut: { start: 202.5, length: 25 },
  },
  {
    slot: 'crickets',
    title: 'Northern California Crickets',
    page: 'https://freesound.org/people/ellie.vanderlip/sounds/704381/',
    preview: 'https://cdn.freesound.org/previews/704/704381_8525021-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/704/704381_8525021-hq.mp3',
    author: 'ellie.vanderlip',
    licence: 'CC0',
    seconds: 115.9,
    rating: 4.7,
    ratings: 77,
    why: 'Dense suburban summer-night cricket chorus; cut avoids the plane at the start and the one around 65-100 s',
    cut: { start: 12, length: 25 },
  },
  {
    slot: 'crickets',
    title: 'Night Ambience 01 - Aug 2 2013 - Back Yard',
    page: 'https://freesound.org/people/rgbrobot/sounds/195969/',
    preview: 'https://cdn.freesound.org/previews/195/195969_3447639-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/195/195969_3447639-hq.mp3',
    author: 'rgbrobot',
    licence: 'CC0',
    seconds: 509.5,
    rating: 4.9,
    ratings: 69,
    why: 'Summer evening backyard crickets and cicadas, very steady; avoid 280-345 s (louder event)',
    cut: { start: 160, length: 25 },
  },
  {
    slot: 'crickets',
    title: 'Crickets during the night, close to the beach in Mexico',
    page: 'https://freesound.org/people/felix.blume/sounds/479041/',
    preview: 'https://cdn.freesound.org/previews/479/479041_1661766-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/479/479041_1661766-hq.mp3',
    author: 'felix.blume',
    licence: 'CC0',
    seconds: 525.8,
    rating: 4.8,
    ratings: 25,
    why: 'Night crickets close to a Mexican beach with soft Pacific surf; fits the resort',
    cut: { start: 138, length: 25 },
  },
  {
    slot: 'cicadas',
    title: 'cicadas.wav',
    page: 'https://freesound.org/people/laughatlantic/sounds/320113/',
    preview: 'https://cdn.freesound.org/previews/320/320113_3713344-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/320/320113_3713344-hq.mp3',
    author: 'laughatlantic',
    licence: 'CC0',
    seconds: 41.5,
    rating: 4.7,
    ratings: 28,
    why: 'Provence cicadas, classic Mediterranean summer drone',
    cut: { start: 8, length: 25 },
  },
  {
    slot: 'cicadas',
    title: 'Summer countryside ambience in south of France',
    page: 'https://freesound.org/people/felix.blume/sounds/234337/',
    preview: 'https://cdn.freesound.org/previews/234/234337_1661766-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/234/234337_1661766-hq.mp3',
    author: 'felix.blume',
    licence: 'CC0',
    seconds: 180.3,
    rating: 4.7,
    ratings: 16,
    why: 'Single cicada drone, south of France countryside, extremely steady level',
    cut: { start: 115, length: 25 },
  },
  {
    slot: 'cicadas',
    title: 'cicadas',
    page: 'https://freesound.org/people/kostasvomvolos/sounds/234878/',
    preview: 'https://cdn.freesound.org/previews/234/234878_5697-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/234/234878_5697-hq.mp3',
    author: 'kostasvomvolos',
    licence: 'CC0',
    seconds: 79.0,
    rating: 4.9,
    ratings: 11,
    why: 'Cicadas on Naxos, Greece; steady chorus',
    cut: { start: 48, length: 25 },
  },
  {
    slot: 'crowd',
    title: 'geroezemoes.wav',
    page: 'https://freesound.org/people/gecop/sounds/640254/',
    preview: 'https://cdn.freesound.org/previews/640/640254_3562198-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/640/640254_3562198-hq.mp3',
    author: 'gecop',
    licence: 'CC0',
    seconds: 120.8,
    rating: 4.8,
    ratings: 18,
    why: 'Distant group chatter (Flemish), no words intelligible; steady murmur',
    cut: { start: 80, length: 25 },
  },
  {
    slot: 'crowd',
    title: 'city_park_ambience_busy.wav',
    page: 'https://freesound.org/people/sphion/sounds/153554/',
    preview: 'https://cdn.freesound.org/previews/153/153554_2783336-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/153/153554_2783336-hq.mp3',
    author: 'sphion',
    licence: 'CC0',
    seconds: 94.2,
    rating: 4.7,
    ratings: 19,
    why: 'Busy city park, people chilling and chatting; cut avoids louder spikes at ~15-20 s and ~85 s',
    cut: { start: 28.5, length: 25 },
  },
  {
    slot: 'crowd',
    title: 'OCEAN Large beach with medium crowd.wav',
    page: 'https://freesound.org/people/nicoproson/sounds/648488/',
    preview: 'https://cdn.freesound.org/previews/648/648488_457982-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/648/648488_457982-hq.mp3',
    author: 'nicoproson',
    licence: 'CC0',
    seconds: 243.0,
    rating: 4.8,
    ratings: 4,
    why: 'Large beach with a medium crowd and surf; thematically ideal but only 4 ratings',
    cut: { start: 189.5, length: 25 },
  },
  {
    slot: 'children',
    title: 'AMB_Playground_Kids_Playing_001.wav',
    page: 'https://freesound.org/people/conleec/sounds/159735/',
    preview: 'https://cdn.freesound.org/previews/159/159735_221578-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/159/159735_221578-hq.mp3',
    author: 'conleec',
    licence: 'CC0',
    seconds: 249.2,
    rating: 4.6,
    ratings: 20,
    why: 'Medium-distant children on a playground, clean with minimal traffic; quiet, needs gain',
    cut: { start: 134.5, length: 25 },
  },
  {
    slot: 'children',
    title: 'playground',
    page: 'https://freesound.org/people/bruno.auzet/sounds/555053/',
    preview: 'https://cdn.freesound.org/previews/555/555053_11519060-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/555/555053_11519060-hq.mp3',
    author: 'bruno.auzet',
    licence: 'CC0',
    seconds: 255.1,
    rating: 4.8,
    ratings: 27,
    why: 'Playground heard from across a road in rural Brittany; wide, distant; two cars pass somewhere in the file',
    cut: { start: 136.5, length: 25 },
  },
  {
    slot: 'children',
    title: 'Playground for children in Romania',
    page: 'https://freesound.org/people/felix.blume/sounds/238549/',
    preview: 'https://cdn.freesound.org/previews/238/238549_1661766-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/238/238549_1661766-hq.mp3',
    author: 'felix.blume',
    licence: 'CC0',
    seconds: 180.9,
    rating: 4.6,
    ratings: 25,
    why: 'Children playing in a park playground in Romania, livelier with some screams',
    cut: { start: 122, length: 25 },
  },
  {
    slot: 'swimmers',
    title: 'Swimming pool outdoor in Romania during the summer',
    page: 'https://freesound.org/people/felix.blume/sounds/238386/',
    preview: 'https://cdn.freesound.org/previews/238/238386_1661766-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/238/238386_1661766-hq.mp3',
    author: 'felix.blume',
    licence: 'CC0',
    seconds: 180.3,
    rating: 4.9,
    ratings: 25,
    why: 'Outdoor summer pool: young voices, splashes, water sounds; best rated',
    cut: { start: 138.5, length: 25 },
  },
  {
    slot: 'swimmers',
    title: 'outdoor pool.wav',
    page: 'https://freesound.org/people/bruno.auzet/sounds/529787/',
    preview: 'https://cdn.freesound.org/previews/529/529787_11519060-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/529/529787_11519060-hq.mp3',
    author: 'bruno.auzet',
    licence: 'CC0',
    seconds: 188.4,
    rating: 5.0,
    ratings: 8,
    why: 'Outdoor pool with children swimming and diving, some adults, birds',
    cut: { start: 60, length: 25 },
  },
  {
    slot: 'swimmers',
    title: 'Families Playing At The Beach With Children.wav',
    page: 'https://freesound.org/people/kaldark/sounds/240331/',
    preview: 'https://cdn.freesound.org/previews/240/240331_2302469-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/240/240331_2302469-hq.mp3',
    author: 'kaldark',
    licence: 'CC0',
    seconds: 55.1,
    rating: 4.6,
    ratings: 8,
    why: 'Packed lakeside beach heard across the water: families, distant laughter and splashing',
    cut: { start: 15, length: 25 },
  },
  {
    slot: 'cafe',
    title: 'Cafe/Coffee shop',
    page: 'https://freesound.org/people/Ultra-Edward/sounds/823831/',
    preview: 'https://cdn.freesound.org/previews/823/823831_16786392-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/823/823831_16786392-hq.mp3',
    author: 'Ultra-Edward',
    licence: 'CC0',
    seconds: 60.0,
    rating: 5.0,
    ratings: 9,
    why: 'customers chatting, orders taken, drinks made; no music, says the author',
    cut: { start: 26, length: 25 },
  },
  {
    slot: 'cafe',
    title: 'OimachiExcelsiorCafe120.wav',
    page: 'https://freesound.org/people/markystar/sounds/42194/',
    preview: 'https://cdn.freesound.org/previews/42/42194_384438-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/42/42194_384438-hq.mp3',
    author: 'markystar',
    licence: 'CC0',
    seconds: 119.3,
    rating: 4.2,
    ratings: 24,
    why: 'Tokyo coffee shop: espresso drinks, cleaning, murmured Japanese; very even',
    cut: { start: 71, length: 25 },
  },
  {
    slot: 'cafe',
    title: 'Coffee Shop.wav',
    page: 'https://freesound.org/people/Trainscough5407/sounds/404478/',
    preview: 'https://cdn.freesound.org/previews/404/404478_5200244-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/404/404478_5200244-hq.mp3',
    author: 'Trainscough5407',
    licence: 'CC0',
    seconds: 60.1,
    rating: 4.8,
    ratings: 14,
    why: 'generic well-rated coffee shop; cut avoids the fade-out',
    cut: { start: 15, length: 25 },
  },
  {
    slot: 'restaurant',
    title: 'Dinner Atmo.wav',
    page: 'https://freesound.org/people/burkay/sounds/325558/',
    preview: 'https://cdn.freesound.org/previews/325/325558_760102-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/325/325558_760102-hq.mp3',
    author: 'burkay',
    licence: 'CC0',
    seconds: 72.6,
    rating: 4.8,
    ratings: 31,
    why: 'dinner party: talk and cutlery; fades at both ends avoided',
    cut: { start: 40, length: 25 },
  },
  {
    slot: 'restaurant',
    title: 'Bustling Cafe Ambience',
    page: 'https://freesound.org/people/Talitha5/sounds/509950/',
    preview: 'https://cdn.freesound.org/previews/509/509950_4458028-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/509/509950_4458028-hq.mp3',
    author: 'Talitha5',
    licence: 'CC0',
    seconds: 30.9,
    rating: 4.8,
    ratings: 31,
    why: 'indistinct voices, plates and silverware; very steady',
    cut: { start: 3, length: 25 },
  },
  {
    slot: 'restaurant',
    title: 'Restaurant Ambience 12.m4a',
    page: 'https://freesound.org/people/callyrobyn/sounds/512367/',
    preview: 'https://cdn.freesound.org/previews/512/512367_4821029-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/512/512367_4821029-hq.mp3',
    author: 'callyrobyn',
    licence: 'CC0',
    seconds: 40.4,
    rating: 4.7,
    ratings: 28,
    why: 'talk and dishes clinking, even level',
    cut: { start: 5, length: 25 },
  },
  {
    slot: 'bar',
    title: 'Crowded Bar - Ambient Loop',
    page: 'https://freesound.org/people/gagehurley78/sounds/397569/',
    preview: 'https://cdn.freesound.org/previews/397/397569_6382166-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/397/397569_6382166-hq.mp3',
    author: 'gagehurley78',
    licence: 'CC0',
    seconds: 56.0,
    rating: 4.8,
    ratings: 18,
    why: 'crowd with glasses and drinks; the author says it loops seamlessly',
    cut: { start: 24, length: 25 },
  },
  {
    slot: 'bar',
    title: 'Ambience_Bar_No_Music.wav',
    page: 'https://freesound.org/people/Dokuta_Gerovv/sounds/661686/',
    preview: 'https://cdn.freesound.org/previews/661/661686_11310256-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/661/661686_11310256-hq.mp3',
    author: 'Dokuta_Gerovv',
    licence: 'CC0',
    seconds: 40.8,
    rating: 4.1,
    ratings: 8,
    why: 'outdoor bar without music: chatter and cups; suits a beach bar',
    cut: { start: 9, length: 25 },
  },
  {
    slot: 'bar',
    title: 'Mines a pint',
    page: 'https://freesound.org/people/apintofmild/sounds/839104/',
    preview: 'https://cdn.freesound.org/previews/839/839104_9813501-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/839/839104_9813501-hq.mp3',
    author: 'apintofmild',
    licence: 'CC0',
    seconds: 60.9,
    rating: 4.3,
    ratings: 6,
    why: 'crowded pub burble, steady, recorded hot',
    cut: { start: 33, length: 25 },
  },
  {
    slot: 'snack',
    title: 'deep-fryer_sizzle.wav',
    page: 'https://freesound.org/people/Audeption/sounds/455653/',
    preview: 'https://cdn.freesound.org/previews/455/455653_8323418-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/455/455653_8323418-hq.mp3',
    author: 'Audeption',
    licence: 'CC0',
    seconds: 59.8,
    rating: 4.3,
    ratings: 12,
    why: 'two snack-bar deep fryers sizzling; cut avoids the fade-out',
    cut: { start: 21, length: 25 },
  },
  {
    slot: 'snack',
    title: 'Asian Restaurant. wav',
    page: 'https://freesound.org/people/gusgus26/sounds/414297/',
    preview: 'https://cdn.freesound.org/previews/414/414297_2147722-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/414/414297_2147722-hq.mp3',
    author: 'gusgus26',
    licence: 'CC0',
    seconds: 26.9,
    rating: 4.9,
    ratings: 16,
    why: 'fast-food kitchen frying with chatter behind; the closest to a busy counter',
    cut: { start: 3, length: 22 },
  },
  {
    slot: 'snack',
    title: 'Deep Frying French Fries.wav',
    page: 'https://freesound.org/people/jbez1/sounds/510835/',
    preview: 'https://cdn.freesound.org/previews/510/510835_10953259-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/510/510835_10953259-hq.mp3',
    author: 'jbez1',
    licence: 'CC0',
    seconds: 23.1,
    rating: 5.0,
    ratings: 12,
    why: 'clean, steady fries sizzling; short, the whole file',
    cut: { start: 0, length: 23 },
  },
  {
    slot: 'shop',
    title: 'Supermarket Checkout .wav',
    page: 'https://freesound.org/people/hubyduby/sounds/148410/',
    preview: 'https://cdn.freesound.org/previews/148/148410_822206-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/148/148410_822206-hq.mp3',
    author: 'hubyduby',
    licence: 'CC0',
    seconds: 60.7,
    rating: 4.8,
    ratings: 4,
    why: 'checkout line with scanner beeps; fridge hum underneath',
    cut: { start: 6, length: 25 },
  },
  {
    slot: 'shop',
    title: 'Supermarket Ambience',
    page: 'https://freesound.org/people/neilraouf/sounds/617520/',
    preview: 'https://cdn.freesound.org/previews/617/617520_2639035-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/617/617520_2639035-hq.mp3',
    author: 'neilraouf',
    licence: 'CC0',
    seconds: 56.0,
    rating: 5.0,
    ratings: 7,
    why: 'supermarket tagged cash register and checkout; even level',
    cut: { start: 16, length: 25 },
  },
  {
    slot: 'shop',
    title: 'Supermarket',
    page: 'https://freesound.org/people/Soundkrampf/sounds/237331/',
    preview: 'https://cdn.freesound.org/previews/237/237331_3435865-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/237/237331_3435865-hq.mp3',
    author: 'Soundkrampf',
    licence: 'CC0',
    seconds: 68.0,
    rating: 4.6,
    ratings: 34,
    why: 'the most-rated generic supermarket atmo, very steady',
    cut: { start: 4, length: 25 },
  },
  {
    slot: 'arcade',
    title: 'Arcade Ambience 3',
    page: 'https://freesound.org/people/maxstcroix/sounds/343151/',
    preview: 'https://cdn.freesound.org/previews/343/343151_1928753-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/343/343151_1928753-hq.mp3',
    author: 'maxstcroix',
    licence: 'CC0',
    seconds: 84.4,
    rating: 4.8,
    ratings: 21,
    why: 'seaside arcade, machines and coins; cut stays in the even opening',
    cut: { start: 2, length: 25 },
  },
  {
    slot: 'arcade',
    title: 'arcade.wav',
    page: 'https://freesound.org/people/mrmayo/sounds/74913/',
    preview: 'https://cdn.freesound.org/previews/74/74913_271213-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/74/74913_271213-hq.mp3',
    author: 'mrmayo',
    licence: 'CC0',
    seconds: 60.3,
    rating: 4.9,
    ratings: 20,
    why: 'boardwalk arcade with video games and slot machines',
    cut: { start: 31, length: 25 },
  },
  {
    slot: 'arcade',
    title: 'arcade sound.wav',
    page: 'https://freesound.org/people/vanceparley/sounds/411444/',
    preview: 'https://cdn.freesound.org/previews/411/411444_5861165-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/411/411444_5861165-hq.mp3',
    author: 'vanceparley',
    licence: 'CC0',
    seconds: 85.6,
    rating: 4.8,
    ratings: 27,
    why: 'inside a game centre, dense bleeps',
    cut: { start: 53, length: 25 },
  },
  {
    slot: 'gym',
    title: 'gym recording',
    page: 'https://freesound.org/people/wdmatheson/sounds/341181/',
    preview: 'https://cdn.freesound.org/previews/341/341181_5699463-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/341/341181_5699463-hq.mp3',
    author: 'wdmatheson',
    licence: 'CC0',
    seconds: 66.6,
    rating: 4.8,
    ratings: 24,
    why: 'gym field recording with people, steady; music not ruled out',
    cut: { start: 10, length: 25 },
  },
  {
    slot: 'gym',
    title: 'gym.wav',
    page: 'https://freesound.org/people/mjaltakona/sounds/441502/',
    preview: 'https://cdn.freesound.org/previews/441/441502_8511224-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/441/441502_8511224-hq.mp3',
    author: 'mjaltakona',
    licence: 'CC0',
    seconds: 111.9,
    rating: 4.7,
    ratings: 7,
    why: 'gym tagged weights and people; long, plenty of choice',
    cut: { start: 19, length: 25 },
  },
  {
    slot: 'gym',
    title: 'TheGym.wav',
    page: 'https://freesound.org/people/jfajner/sounds/70933/',
    preview: 'https://cdn.freesound.org/previews/70/70933_608703-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/70/70933_608703-hq.mp3',
    author: 'jfajner',
    licence: 'CC0',
    seconds: 42.1,
    rating: 4.4,
    ratings: 42,
    why: 'the most-rated gym ambience, even level',
    cut: { start: 12, length: 25 },
  },
  {
    slot: 'spa',
    title: 'Koshi Wind Chimes, Medium',
    page: 'https://freesound.org/people/Kinoton/sounds/378431/',
    preview: 'https://cdn.freesound.org/previews/378/378431_2247456-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/378/378431_2247456-hq.mp3',
    author: 'Kinoton',
    licence: 'CC0',
    seconds: 77.3,
    rating: 4.9,
    ratings: 27,
    why: 'soft bamboo Koshi chimes, clean',
    cut: { start: 3, length: 25 },
  },
  {
    slot: 'spa',
    title: 'Fountain Babbling',
    page: 'https://freesound.org/people/CheatinSloth/sounds/738777/',
    preview: 'https://cdn.freesound.org/previews/738/738777_13230621-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/738/738777_13230621-hq.mp3',
    author: 'CheatinSloth',
    licence: 'CC0',
    seconds: 28.8,
    rating: 5.0,
    ratings: 10,
    why: 'very steady trickling water; could be layered under a chime',
    cut: { start: 2, length: 25 },
  },
  {
    slot: 'spa',
    title: 'KOSHI bell WATER',
    page: 'https://freesound.org/people/Marcysia/sounds/653636/',
    preview: 'https://cdn.freesound.org/previews/653/653636_10726460-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/653/653636_10726460-hq.mp3',
    author: 'Marcysia',
    licence: 'CC0',
    seconds: 113.5,
    rating: 4.9,
    ratings: 14,
    why: "gentle Koshi 'Water' chime (the model's name; no water in it)",
    cut: { start: 84, length: 25 },
  },
  {
    slot: 'pool',
    title: 'Swimming pool outdoor in Romania during the summer',
    page: 'https://freesound.org/people/felix.blume/sounds/238386/',
    preview: 'https://cdn.freesound.org/previews/238/238386_1661766-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/238/238386_1661766-hq.mp3',
    author: 'felix.blume',
    licence: 'CC0',
    seconds: 180.3,
    rating: 4.9,
    ratings: 25,
    why: 'Outdoor pool in summer, kids and teens, splashes; well rated MS field recording',
    cut: { start: 38, length: 25 },
  },
  {
    slot: 'pool',
    title: 'Swimming Pool',
    page: 'https://freesound.org/people/Fission9/sounds/565475/',
    preview: 'https://cdn.freesound.org/previews/565/565475_9395330-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/565/565475_9395330-hq.mp3',
    author: 'Fission9',
    licence: 'CC0',
    seconds: 61.7,
    rating: 5.0,
    ratings: 6,
    why: 'Lots of splashing and kids shouting; first 25 s are quieter, cut from the busier second half',
    cut: { start: 26, length: 25 },
  },
  {
    slot: 'pool',
    title: 'Swimming pool',
    page: 'https://freesound.org/people/eguaus/sounds/331882/',
    preview: 'https://cdn.freesound.org/previews/331/331882_40875-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/331/331882_40875-hq.mp3',
    author: 'eguaus',
    licence: 'CC0',
    seconds: 121.2,
    rating: 4.7,
    ratings: 13,
    why: 'Binaural public pool with children playing on a summer afternoon',
    cut: { start: 10, length: 25 },
  },
  {
    slot: 'kids',
    title: 'schoolyard playing children atmo',
    page: 'https://freesound.org/people/Garuda1982/sounds/538220/',
    preview: 'https://cdn.freesound.org/previews/538/538220_2061858-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/538/538220_2061858-hq.mp3',
    author: 'Garuda1982',
    licence: 'CC0',
    seconds: 79.9,
    rating: 4.7,
    ratings: 18,
    why: 'Schoolyard children playing, steady walla without a dominant voice',
    cut: { start: 22, length: 25 },
  },
  {
    slot: 'kids',
    title: 'Playground for children in Romania',
    page: 'https://freesound.org/people/felix.blume/sounds/238549/',
    preview: 'https://cdn.freesound.org/previews/238/238549_1661766-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/238/238549_1661766-hq.mp3',
    author: 'felix.blume',
    licence: 'CC0',
    seconds: 180.9,
    rating: 4.6,
    ratings: 25,
    why: 'Children playing and screaming in a park playground, clean MS recording',
    cut: { start: 149, length: 25 },
  },
  {
    slot: 'kids',
    title: 'Playground noises in Luxembourg Gardens',
    page: 'https://freesound.org/people/Mxsmanic/sounds/162318/',
    preview: 'https://cdn.freesound.org/previews/162/162318_630368-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/162/162318_630368-hq.mp3',
    author: 'Mxsmanic',
    licence: 'CC0',
    seconds: 120.0,
    rating: 4.5,
    ratings: 34,
    why: 'Luxembourg Gardens playground with occasional metallic play-equipment clinks',
    cut: { start: 10, length: 25 },
  },
  {
    slot: 'tennis',
    title: 'play tennis outside atmo',
    page: 'https://freesound.org/people/Garuda1982/sounds/585820/',
    preview: 'https://cdn.freesound.org/previews/585/585820_2061858-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/585/585820_2061858-hq.mp3',
    author: 'Garuda1982',
    licence: 'CC0',
    seconds: 116.8,
    rating: 4.5,
    ratings: 13,
    why: 'Outdoor tennis atmo with regular ball hits throughout, very consistent',
    cut: { start: 70, length: 25 },
  },
  {
    slot: 'tennis',
    title: 'tennis;hitting balls;running;birds;mono.wav',
    page: 'https://freesound.org/people/drewhalasz/sounds/379996/',
    preview: 'https://cdn.freesound.org/previews/379/379996_138-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/379/379996_138-hq.mp3',
    author: 'drewhalasz',
    licence: 'CC0',
    seconds: 83.5,
    rating: 5.0,
    ratings: 6,
    why: 'Tennis hits, running and birds, mono shotgun; dense rally stretch',
    cut: { start: 45, length: 25 },
  },
  {
    slot: 'tennis',
    title: 'tennis match.wav',
    page: 'https://freesound.org/people/huubjeroen/sounds/114052/',
    preview: 'https://cdn.freesound.org/previews/114/114052_190760-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/114/114052_190760-hq.mp3',
    author: 'huubjeroen',
    licence: 'CC0',
    seconds: 298.4,
    rating: 4.8,
    ratings: 38,
    why: 'Broadcast-mixed pro match (ATP Rotterdam) with crowd; may contain umpire calls, check the cut',
    cut: { start: 205, length: 25 },
  },
  {
    slot: 'ballcourt',
    title:
      'crowd ext walled basketball and tennis court playing different sports fence NYC, USA.flac',
    page: 'https://freesound.org/people/kyles/sounds/452928/',
    preview: 'https://cdn.freesound.org/previews/452/452928_612689-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/452/452928_612689-hq.mp3',
    author: 'kyles',
    licence: 'CC0',
    seconds: 122.3,
    rating: 5.0,
    ratings: 5,
    why: 'Outdoor walled court in NYC, basketball and tennis being played, dribbles and calls',
    cut: { start: 20, length: 25 },
  },
  {
    slot: 'ballcourt',
    title: 'Moscow_Strogino_Volleyball',
    page: 'https://freesound.org/people/softwalls/sounds/384659/',
    preview: 'https://cdn.freesound.org/previews/384/384659_6070740-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/384/384659_6070740-hq.mp3',
    author: 'softwalls',
    licence: 'CC0',
    seconds: 191.2,
    rating: 4.7,
    ratings: 3,
    why: 'Volleyball game in a park with birds and light city hum',
    cut: { start: 65, length: 25 },
  },
  {
    slot: 'ballcourt',
    title: 'Street basketball court in the summer at twilight',
    page: 'https://freesound.org/people/lastraindrop/sounds/749951/',
    preview: 'https://cdn.freesound.org/previews/749/749951_12768873-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/749/749951_12768873-hq.mp3',
    author: 'lastraindrop',
    licence: 'CC0',
    seconds: 319.0,
    rating: 4.7,
    ratings: 3,
    why: 'Street basketball court on a summer evening with cicadas; passersby audible',
    cut: { start: 20, length: 25 },
  },
  {
    slot: 'minigolf',
    title: 'putt.wav',
    page: 'https://freesound.org/people/170129/sounds/408260/',
    preview: 'https://cdn.freesound.org/previews/408/408260_7906405-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/408/408260_7906405-hq.mp3',
    author: '170129',
    licence: 'CC0',
    seconds: 15.5,
    rating: 4.8,
    ratings: 9,
    why: 'Close recording of several golf putts (one-shots, no ambience bed)',
    cut: { start: 0, length: 15.5 },
  },
  {
    slot: 'minigolf',
    title: 'Golf ball in hole.wav',
    page: 'https://freesound.org/people/Scottrex05/sounds/593482/',
    preview: 'https://cdn.freesound.org/previews/593/593482_12595642-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/593/593482_12595642-hq.mp3',
    author: 'Scottrex05',
    licence: 'CC0',
    seconds: 11.0,
    rating: 2.1,
    ratings: 7,
    why: 'Golf ball dropping into the hole; low rating, use as an occasional one-shot',
    cut: { start: 0, length: 11.0 },
  },
  {
    slot: 'minigolf',
    title: 'Golfballs rolling on Wooden Surface.wav',
    page: 'https://freesound.org/people/juanstrydom2002/sounds/655042/',
    preview: 'https://cdn.freesound.org/previews/655/655042_14379945-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/655/655042_14379945-hq.mp3',
    author: 'juanstrydom2002',
    licence: 'CC0',
    seconds: 12.4,
    rating: 4.8,
    ratings: 5,
    why: 'Golf balls rolling on wood, could stand in for mini-golf lane rolls',
    cut: { start: 0, length: 12.4 },
  },
  {
    slot: 'boats',
    title: 'Dock,Wood,Creak,Water,Laping.wav',
    page: 'https://freesound.org/people/Filipe%20Chagas/sounds/91912/',
    preview: 'https://cdn.freesound.org/previews/91/91912_1512131-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/91/91912_1512131-hq.mp3',
    author: 'Filipe Chagas',
    licence: 'CC0',
    seconds: 228.1,
    rating: 4.5,
    ratings: 41,
    why: 'Yacht club dock: wooden creaks and rhythmic water lapping, popular',
    cut: { start: 40, length: 25 },
  },
  {
    slot: 'boats',
    title: 'grincements_helvetia.aif',
    page: 'https://freesound.org/people/f_ilippo/sounds/59160/',
    preview: 'https://cdn.freesound.org/previews/59/59160_745228-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/59/59160_745228-hq.mp3',
    author: 'f_ilippo',
    licence: 'CC0',
    seconds: 90.4,
    rating: 4.5,
    ratings: 31,
    why: 'Moored paddle steamer pitching on small waves, creaks and mooring-rope groans',
    cut: { start: 0, length: 25 },
  },
  {
    slot: 'boats',
    title: 'Port la foret.wav',
    page: 'https://freesound.org/people/bruno.auzet/sounds/570914/',
    preview: 'https://cdn.freesound.org/previews/570/570914_11519060-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/570/570914_11519060-hq.mp3',
    author: 'bruno.auzet',
    licence: 'CC0',
    seconds: 52.2,
    rating: 4.8,
    ratings: 6,
    why: 'Floating dock with water clapotis and wind in boat rigging (a dog/voice briefly per description)',
    cut: { start: 3, length: 25 },
  },
  {
    slot: 'reception',
    title: 'S14-03 Large hotel lobby.wav',
    page: 'https://freesound.org/people/craigsmith/sounds/675171/',
    preview: 'https://cdn.freesound.org/previews/675/675171_2524442-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/675/675171_2524442-hq.mp3',
    author: 'craigsmith',
    licence: 'CC0',
    seconds: 22.5,
    rating: 5.0,
    ratings: 3,
    why: 'Large hotel lobby room tone with light activity; whole file is short',
    cut: { start: 0, length: 22.5 },
  },
  {
    slot: 'reception',
    title: 'weeled suitcase.wav',
    page: 'https://freesound.org/people/bruno.auzet/sounds/536590/',
    preview: 'https://cdn.freesound.org/previews/536/536590_11519060-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/536/536590_11519060-hq.mp3',
    author: 'bruno.auzet',
    licence: 'CC0',
    seconds: 55.0,
    rating: 4.8,
    ratings: 15,
    why: 'Wheeled suitcase rolling close up in an airport hall',
    cut: { start: 1, length: 25 },
  },
  {
    slot: 'reception',
    title: '220516 desk bell rings',
    page: 'https://freesound.org/people/TRP/sounds/717564/',
    preview: 'https://cdn.freesound.org/previews/717/717564_97550-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/717/717564_97550-hq.mp3',
    author: 'TRP',
    licence: 'CC0',
    seconds: 50.5,
    rating: 5.0,
    ratings: 7,
    why: 'A few dings of a desk service bell, sparse with silence between',
    cut: { start: 0, length: 30 },
  },
  {
    slot: 'restrooms',
    title: 'AMBRoom-Int_Public Bathroom Ambience_HvD_OwSFX_Loop',
    page: 'https://freesound.org/people/Hano_van_Dalen/sounds/767306/',
    preview: 'https://cdn.freesound.org/previews/767/767306_15758192-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/767/767306_15758192-hq.mp3',
    author: 'Hano_van_Dalen',
    licence: 'CC0',
    seconds: 133.0,
    ratings: 0,
    why: 'Public bathroom ambience: sink running, hand dryer blasts, soap dispenser, flush, echoes',
    cut: { start: 47, length: 30 },
  },
  {
    slot: 'restrooms',
    title: 'hand_dryer.wav',
    page: 'https://freesound.org/people/4estaciones/sounds/186453/',
    preview: 'https://cdn.freesound.org/previews/186/186453_3459121-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/186/186453_3459121-hq.mp3',
    author: '4estaciones',
    licence: 'CC0',
    seconds: 33.4,
    rating: 4.7,
    ratings: 3,
    why: 'Continuous hand dryer in a public toilet',
    cut: { start: 2, length: 28 },
  },
  {
    slot: 'restrooms',
    title: 'Toilet Atmosphere in Restaurant or Bar 1',
    page: 'https://freesound.org/people/leonelmail/sounds/427853/',
    preview: 'https://cdn.freesound.org/previews/427/427853_4437257-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/427/427853_4437257-hq.mp3',
    author: 'leonelmail',
    licence: 'CC0',
    seconds: 224.0,
    rating: 5.0,
    ratings: 5,
    why: 'Restaurant toilet: flush system, drips, air-conditioning bed',
    cut: { start: 0, length: 25 },
  },
  {
    slot: 'bonfire',
    title: 'bonfire flames sizzling',
    page: 'https://freesound.org/people/florianreichelt/sounds/563764/',
    preview: 'https://cdn.freesound.org/previews/563/563764_6253486-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/563/563764_6253486-hq.mp3',
    author: 'florianreichelt',
    licence: 'CC0',
    seconds: 50.0,
    rating: 4.3,
    ratings: 59,
    why: 'A bonfire by name: steady crackle and sizzle; the steadiest 20 s of the three (1.1 dB RMS spread)',
    cut: { start: 27, length: 20 },
  },
  {
    slot: 'bonfire',
    title: 'Campfire 02',
    page: 'https://freesound.org/people/HECKFRICKER/sounds/729396/',
    preview: 'https://cdn.freesound.org/previews/729/729396_12863902-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/729/729396_12863902-hq.mp3',
    author: 'HECKFRICKER',
    licence: 'CC0',
    seconds: 267.6,
    ratings: 102,
    why: 'Close campfire in a tyre rim, a low roar under the crackle; bigger than the torch; quiet, so it leans on the loudness pass',
    cut: { start: 26, length: 20 },
  },
  {
    slot: 'bonfire',
    title: 'Campfire Close Crackling Sticks.mp3',
    page: 'https://freesound.org/people/FunWithSound/sounds/588401/',
    preview: 'https://cdn.freesound.org/previews/588/588401_6456158-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/588/588401_6456158-hq.mp3',
    author: 'FunWithSound',
    licence: 'CC0',
    seconds: 185.6,
    rating: 4.5,
    ratings: 46,
    why: 'Close stick fire, busy with crackles and pops; a pocket recorder, so a little hiss',
    cut: { start: 115, length: 20 },
  },
  {
    slot: 'fountain',
    title: 'Fountain_2.wav',
    page: 'https://freesound.org/people/skyko/sounds/169254/',
    preview: 'https://cdn.freesound.org/previews/169/169254_1391822-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/169/169254_1391822-hq.mp3',
    author: 'skyko',
    licence: 'CC0',
    seconds: 60.9,
    rating: 5.0,
    ratings: 26,
    why: 'Small fountain, continuous splashing, top rated and very steady',
    cut: { start: 29, length: 25 },
  },
  {
    slot: 'fountain',
    title: 'Fountain_1.wav',
    page: 'https://freesound.org/people/skyko/sounds/169250/',
    preview: 'https://cdn.freesound.org/previews/169/169250_1391822-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/169/169250_1391822-hq.mp3',
    author: 'skyko',
    licence: 'CC0',
    seconds: 60.7,
    rating: 4.8,
    ratings: 26,
    why: 'Small fountain, slightly brighter splash; most downloaded',
    cut: { start: 27.5, length: 25 },
  },
  {
    slot: 'fountain',
    title: 'Garden Fountain.wav',
    page: 'https://freesound.org/people/kkingotu/sounds/434815/',
    preview: 'https://cdn.freesound.org/previews/434/434815_8867062-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/434/434815_8867062-hq.mp3',
    author: 'kkingotu',
    licence: 'CC0',
    seconds: 82.6,
    rating: 4.8,
    ratings: 5,
    why: 'Two-tier garden fountain; quiet recording, needs gain',
    cut: { start: 54, length: 25 },
  },
  {
    slot: 'torch',
    title: 'fire ambience, flames, crackles, pops, burning',
    page: 'https://freesound.org/people/ahriik/sounds/508110/',
    preview: 'https://cdn.freesound.org/previews/508/508110_6657854-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/508/508110_6657854-hq.mp3',
    author: 'ahriik',
    licence: 'CC0',
    seconds: 27.0,
    rating: 4.9,
    ratings: 72,
    why: 'Close fire with small crackles and pops, no roar; MKH-50 clean',
    cut: { start: 0, length: 27 },
  },
  {
    slot: 'torch',
    title: 'Fire Crackling 01.wav',
    page: 'https://freesound.org/people/kingsrow/sounds/181563/',
    preview: 'https://cdn.freesound.org/previews/181/181563_1857065-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/181/181563_1857065-hq.mp3',
    author: 'kingsrow',
    licence: 'CC0',
    seconds: 34.2,
    rating: 4.6,
    ratings: 97,
    why: 'Small fire crackling and burning, very popular; whole file is usable',
    cut: { start: 2, length: 30 },
  },
  {
    slot: 'torch',
    title: 'Campfire (Position 2)',
    page: 'https://freesound.org/people/SKrafft/sounds/681367/',
    preview: 'https://cdn.freesound.org/previews/681/681367_5752443-hq.mp3',
    fetch: 'https://cdn.freesound.org/previews/681/681367_5752443-hq.mp3',
    author: 'SKrafft',
    licence: 'CC0',
    seconds: 22.1,
    rating: 4.8,
    ratings: 41,
    why: 'Quiet late-night campfire; has one or two louder pops',
    cut: { start: 0, length: 22 },
  },
  {
    slot: 'place',
    title: 'Impact Sounds / impactWood_heavy_000.ogg',
    page: 'https://kenney.nl/assets/impact-sounds',
    preview: '',
    fetch:
      'https://kenney.nl/media/pages/assets/impact-sounds/87b4ddecda-1677589768/kenney_impact-sounds.zip',
    member: 'Audio/impactWood_heavy_000.ogg',
    author: 'Kenney',
    licence: 'CC0',
    seconds: 0.31,
    why: 'solid heavy wooden thunk',
  },
  {
    slot: 'place',
    title: 'Impact Sounds / impactWood_heavy_001.ogg',
    page: 'https://kenney.nl/assets/impact-sounds',
    preview: '',
    fetch:
      'https://kenney.nl/media/pages/assets/impact-sounds/87b4ddecda-1677589768/kenney_impact-sounds.zip',
    member: 'Audio/impactWood_heavy_001.ogg',
    author: 'Kenney',
    licence: 'CC0',
    seconds: 0.31,
    why: 'same set, variant',
  },
  {
    slot: 'place',
    title: 'Impact Sounds / impactWood_heavy_002.ogg',
    page: 'https://kenney.nl/assets/impact-sounds',
    preview: '',
    fetch:
      'https://kenney.nl/media/pages/assets/impact-sounds/87b4ddecda-1677589768/kenney_impact-sounds.zip',
    member: 'Audio/impactWood_heavy_002.ogg',
    author: 'Kenney',
    licence: 'CC0',
    seconds: 0.31,
    why: 'same set, variant',
  },
  {
    slot: 'place',
    title: 'Impact Sounds / impactWood_medium_000.ogg',
    page: 'https://kenney.nl/assets/impact-sounds',
    preview: '',
    fetch:
      'https://kenney.nl/media/pages/assets/impact-sounds/87b4ddecda-1677589768/kenney_impact-sounds.zip',
    member: 'Audio/impactWood_medium_000.ogg',
    author: 'Kenney',
    licence: 'CC0',
    seconds: 0.3,
    why: 'lighter wooden knock, for small objects',
  },
  {
    slot: 'pave',
    title: 'Impact Sounds / footstep_concrete_000.ogg',
    page: 'https://kenney.nl/assets/impact-sounds',
    preview: '',
    fetch:
      'https://kenney.nl/media/pages/assets/impact-sounds/87b4ddecda-1677589768/kenney_impact-sounds.zip',
    member: 'Audio/footstep_concrete_000.ogg',
    author: 'Kenney',
    licence: 'CC0',
    seconds: 0.11,
    why: 'light stone tap',
  },
  {
    slot: 'pave',
    title: 'Impact Sounds / footstep_concrete_001.ogg',
    page: 'https://kenney.nl/assets/impact-sounds',
    preview: '',
    fetch:
      'https://kenney.nl/media/pages/assets/impact-sounds/87b4ddecda-1677589768/kenney_impact-sounds.zip',
    member: 'Audio/footstep_concrete_001.ogg',
    author: 'Kenney',
    licence: 'CC0',
    seconds: 0.11,
    why: 'same set, variant',
  },
  {
    slot: 'pave',
    title: 'Impact Sounds / footstep_concrete_002.ogg',
    page: 'https://kenney.nl/assets/impact-sounds',
    preview: '',
    fetch:
      'https://kenney.nl/media/pages/assets/impact-sounds/87b4ddecda-1677589768/kenney_impact-sounds.zip',
    member: 'Audio/footstep_concrete_002.ogg',
    author: 'Kenney',
    licence: 'CC0',
    seconds: 0.11,
    why: 'same set, variant',
  },
  {
    slot: 'pave',
    title: 'Impact Sounds / footstep_concrete_003.ogg',
    page: 'https://kenney.nl/assets/impact-sounds',
    preview: '',
    fetch:
      'https://kenney.nl/media/pages/assets/impact-sounds/87b4ddecda-1677589768/kenney_impact-sounds.zip',
    member: 'Audio/footstep_concrete_003.ogg',
    author: 'Kenney',
    licence: 'CC0',
    seconds: 0.11,
    why: 'same set, a fourth variant',
  },
  {
    slot: 'dig',
    title: 'Impact Sounds / impactSoft_heavy_000.ogg',
    page: 'https://kenney.nl/assets/impact-sounds',
    preview: '',
    fetch:
      'https://kenney.nl/media/pages/assets/impact-sounds/87b4ddecda-1677589768/kenney_impact-sounds.zip',
    member: 'Audio/impactSoft_heavy_000.ogg',
    author: 'Kenney',
    licence: 'CC0',
    seconds: 0.51,
    why: 'dull soft thud like earth',
  },
  {
    slot: 'dig',
    title: 'Impact Sounds / impactSoft_heavy_001.ogg',
    page: 'https://kenney.nl/assets/impact-sounds',
    preview: '',
    fetch:
      'https://kenney.nl/media/pages/assets/impact-sounds/87b4ddecda-1677589768/kenney_impact-sounds.zip',
    member: 'Audio/impactSoft_heavy_001.ogg',
    author: 'Kenney',
    licence: 'CC0',
    seconds: 0.57,
    why: 'same set, variant',
  },
  {
    slot: 'dig',
    title: 'Impact Sounds / footstep_snow_000.ogg',
    page: 'https://kenney.nl/assets/impact-sounds',
    preview: '',
    fetch:
      'https://kenney.nl/media/pages/assets/impact-sounds/87b4ddecda-1677589768/kenney_impact-sounds.zip',
    member: 'Audio/footstep_snow_000.ogg',
    author: 'Kenney',
    licence: 'CC0',
    seconds: 0.37,
    why: 'crunchy, granular step, could read as soil',
  },
  {
    slot: 'demolish',
    title: 'Impact Sounds / impactPlank_medium_000.ogg',
    page: 'https://kenney.nl/assets/impact-sounds',
    preview: '',
    fetch:
      'https://kenney.nl/media/pages/assets/impact-sounds/87b4ddecda-1677589768/kenney_impact-sounds.zip',
    member: 'Audio/impactPlank_medium_000.ogg',
    author: 'Kenney',
    licence: 'CC0',
    seconds: 0.78,
    why: 'planks clattering down, longer crash',
  },
  {
    slot: 'demolish',
    title: 'Impact Sounds / impactPlank_medium_001.ogg',
    page: 'https://kenney.nl/assets/impact-sounds',
    preview: '',
    fetch:
      'https://kenney.nl/media/pages/assets/impact-sounds/87b4ddecda-1677589768/kenney_impact-sounds.zip',
    member: 'Audio/impactPlank_medium_001.ogg',
    author: 'Kenney',
    licence: 'CC0',
    seconds: 0.78,
    why: 'same set, variant',
  },
  {
    slot: 'demolish',
    title: 'Impact Sounds / impactMining_000.ogg',
    page: 'https://kenney.nl/assets/impact-sounds',
    preview: '',
    fetch:
      'https://kenney.nl/media/pages/assets/impact-sounds/87b4ddecda-1677589768/kenney_impact-sounds.zip',
    member: 'Audio/impactMining_000.ogg',
    author: 'Kenney',
    licence: 'CC0',
    seconds: 0.94,
    why: 'rock breaking, heavier stone crash',
  },
  {
    slot: 'built',
    title: 'Music Jingles / jingles_STEEL00.ogg',
    page: 'https://kenney.nl/assets/music-jingles',
    preview: '',
    fetch:
      'https://kenney.nl/media/pages/assets/music-jingles/f37e530b9e-1677590399/kenney_music-jingles.zip',
    member: 'Audio/Steel jingles/jingles_STEEL00.ogg',
    author: 'Kenney',
    licence: 'CC0',
    seconds: 0.93,
    why: 'steel-drum jingle, fits the beach theme',
  },
  {
    slot: 'built',
    title: 'Music Jingles / jingles_PIZZI01.ogg',
    page: 'https://kenney.nl/assets/music-jingles',
    preview: '',
    fetch:
      'https://kenney.nl/media/pages/assets/music-jingles/f37e530b9e-1677590399/kenney_music-jingles.zip',
    member: 'Audio/Pizzicato jingles/jingles_PIZZI01.ogg',
    author: 'Kenney',
    licence: 'CC0',
    seconds: 1.0,
    why: 'light pizzicato flourish',
  },
  {
    slot: 'built',
    title: 'Music Jingles / jingles_SAX01.ogg',
    page: 'https://kenney.nl/assets/music-jingles',
    preview: '',
    fetch:
      'https://kenney.nl/media/pages/assets/music-jingles/f37e530b9e-1677590399/kenney_music-jingles.zip',
    member: 'Audio/Sax jingles/jingles_SAX01.ogg',
    author: 'Kenney',
    licence: 'CC0',
    seconds: 0.89,
    why: 'jazzy sax sting',
  },
  {
    slot: 'land',
    title: 'RPG Audio / handleCoins.ogg',
    page: 'https://kenney.nl/assets/rpg-audio',
    preview: '',
    fetch:
      'https://kenney.nl/media/pages/assets/rpg-audio/8e99002d76-1677590336/kenney_rpg-audio.zip',
    member: 'Audio/handleCoins.ogg',
    author: 'Kenney',
    licence: 'CC0',
    seconds: 0.85,
    why: 'handful of coins jingling, reads as a purchase',
  },
  {
    slot: 'land',
    title: 'RPG Audio / handleCoins2.ogg',
    page: 'https://kenney.nl/assets/rpg-audio',
    preview: '',
    fetch:
      'https://kenney.nl/media/pages/assets/rpg-audio/8e99002d76-1677590336/kenney_rpg-audio.zip',
    member: 'Audio/handleCoins2.ogg',
    author: 'Kenney',
    licence: 'CC0',
    seconds: 0.34,
    why: 'shorter coin jingle',
  },
  {
    slot: 'land',
    title: 'Casino Audio / chips-stack-3.ogg',
    page: 'https://kenney.nl/assets/casino-audio',
    preview: '',
    fetch:
      'https://kenney.nl/media/pages/assets/casino-audio/2472606a04-1721639069/kenney_casino-audio.zip',
    member: 'Audio/chips-stack-3.ogg',
    author: 'Kenney',
    licence: 'CC0',
    seconds: 0.37,
    why: 'chips clacking, money-ish',
  },
  {
    slot: 'morning',
    title: 'Music Jingles / jingles_STEEL04.ogg',
    page: 'https://kenney.nl/assets/music-jingles',
    preview: '',
    fetch:
      'https://kenney.nl/media/pages/assets/music-jingles/f37e530b9e-1677590399/kenney_music-jingles.zip',
    member: 'Audio/Steel jingles/jingles_STEEL04.ogg',
    author: 'Kenney',
    licence: 'CC0',
    seconds: 0.91,
    why: 'bright steel-drum jingle for a new day',
  },
  {
    slot: 'morning',
    title: 'Music Jingles / jingles_STEEL05.ogg',
    page: 'https://kenney.nl/assets/music-jingles',
    preview: '',
    fetch:
      'https://kenney.nl/media/pages/assets/music-jingles/f37e530b9e-1677590399/kenney_music-jingles.zip',
    member: 'Audio/Steel jingles/jingles_STEEL05.ogg',
    author: 'Kenney',
    licence: 'CC0',
    seconds: 0.94,
    why: 'alternate steel-drum jingle',
  },
  {
    slot: 'morning',
    title: 'Music Jingles / jingles_PIZZI02.ogg',
    page: 'https://kenney.nl/assets/music-jingles',
    preview: '',
    fetch:
      'https://kenney.nl/media/pages/assets/music-jingles/f37e530b9e-1677590399/kenney_music-jingles.zip',
    member: 'Audio/Pizzicato jingles/jingles_PIZZI02.ogg',
    author: 'Kenney',
    licence: 'CC0',
    seconds: 0.96,
    why: 'bright pizzicato jingle',
  },
  {
    slot: 'day',
    title: 'Music Jingles / jingles_STEEL09.ogg',
    page: 'https://kenney.nl/assets/music-jingles',
    preview: '',
    fetch:
      'https://kenney.nl/media/pages/assets/music-jingles/f37e530b9e-1677590399/kenney_music-jingles.zip',
    member: 'Audio/Steel jingles/jingles_STEEL09.ogg',
    author: 'Kenney',
    licence: 'CC0',
    seconds: 0.59,
    why: 'shortest steel-drum jingle, unobtrusive for a report toast',
  },
  {
    slot: 'day',
    title: 'Music Jingles / jingles_STEEL10.ogg',
    page: 'https://kenney.nl/assets/music-jingles',
    preview: '',
    fetch:
      'https://kenney.nl/media/pages/assets/music-jingles/f37e530b9e-1677590399/kenney_music-jingles.zip',
    member: 'Audio/Steel jingles/jingles_STEEL10.ogg',
    author: 'Kenney',
    licence: 'CC0',
    seconds: 0.91,
    why: 'alternate steel-drum jingle',
  },
  {
    slot: 'day',
    title: 'Music Jingles / jingles_PIZZI04.ogg',
    page: 'https://kenney.nl/assets/music-jingles',
    preview: '',
    fetch:
      'https://kenney.nl/media/pages/assets/music-jingles/f37e530b9e-1677590399/kenney_music-jingles.zip',
    member: 'Audio/Pizzicato jingles/jingles_PIZZI04.ogg',
    author: 'Kenney',
    licence: 'CC0',
    seconds: 0.56,
    why: 'short pizzicato jingle',
  },
  {
    slot: 'click',
    title: 'UI Audio / click1.ogg',
    page: 'https://kenney.nl/assets/ui-audio',
    preview: '',
    fetch:
      'https://kenney.nl/media/pages/assets/ui-audio/490d233f68-1677590494/kenney_ui-audio.zip',
    member: 'Audio/click1.ogg',
    author: 'Kenney',
    licence: 'CC0',
    seconds: 0.09,
    why: 'soft, short UI click',
  },
  {
    slot: 'click',
    title: 'UI Audio / click3.ogg',
    page: 'https://kenney.nl/assets/ui-audio',
    preview: '',
    fetch:
      'https://kenney.nl/media/pages/assets/ui-audio/490d233f68-1677590494/kenney_ui-audio.zip',
    member: 'Audio/click3.ogg',
    author: 'Kenney',
    licence: 'CC0',
    seconds: 0.09,
    why: 'quietest of the click set, good variant',
  },
  {
    slot: 'click',
    title: 'UI Audio / click5.ogg',
    page: 'https://kenney.nl/assets/ui-audio',
    preview: '',
    fetch:
      'https://kenney.nl/media/pages/assets/ui-audio/490d233f68-1677590494/kenney_ui-audio.zip',
    member: 'Audio/click5.ogg',
    author: 'Kenney',
    licence: 'CC0',
    seconds: 0.03,
    why: 'very short tick, third variant',
  },
  {
    slot: 'click',
    title: 'Interface Sounds / click_001.ogg',
    page: 'https://kenney.nl/assets/interface-sounds',
    preview: '',
    fetch:
      'https://kenney.nl/media/pages/assets/interface-sounds/fa43c1dd4d-1677589452/kenney_interface-sounds.zip',
    member: 'Audio/click_001.ogg',
    author: 'Kenney',
    licence: 'CC0',
    seconds: 0.1,
    why: 'alternative click from the other interface pack',
  },
  {
    slot: 'toggle',
    title: 'Interface Sounds / toggle_001.ogg',
    page: 'https://kenney.nl/assets/interface-sounds',
    preview: '',
    fetch:
      'https://kenney.nl/media/pages/assets/interface-sounds/fa43c1dd4d-1677589452/kenney_interface-sounds.zip',
    member: 'Audio/toggle_001.ogg',
    author: 'Kenney',
    licence: 'CC0',
    seconds: 0.14,
    why: 'named toggle click, crisp and short',
  },
  {
    slot: 'toggle',
    title: 'UI Audio / switch1.ogg',
    page: 'https://kenney.nl/assets/ui-audio',
    preview: '',
    fetch:
      'https://kenney.nl/media/pages/assets/ui-audio/490d233f68-1677590494/kenney_ui-audio.zip',
    member: 'Audio/switch1.ogg',
    author: 'Kenney',
    licence: 'CC0',
    seconds: 0.31,
    why: 'mechanical switch flip',
  },
  {
    slot: 'toggle',
    title: 'Interface Sounds / toggle_003.ogg',
    page: 'https://kenney.nl/assets/interface-sounds',
    preview: '',
    fetch:
      'https://kenney.nl/media/pages/assets/interface-sounds/fa43c1dd4d-1677589452/kenney_interface-sounds.zip',
    member: 'Audio/toggle_003.ogg',
    author: 'Kenney',
    licence: 'CC0',
    seconds: 0.14,
    why: 'alternate toggle click',
  },
  {
    slot: 'refused',
    title: 'Interface Sounds / error_008.ogg',
    page: 'https://kenney.nl/assets/interface-sounds',
    preview: '',
    fetch:
      'https://kenney.nl/media/pages/assets/interface-sounds/fa43c1dd4d-1677589452/kenney_interface-sounds.zip',
    member: 'Audio/error_008.ogg',
    author: 'Kenney',
    licence: 'CC0',
    seconds: 0.14,
    why: 'quietest, shortest error blip; gentle no',
  },
  {
    slot: 'refused',
    title: 'Interface Sounds / error_004.ogg',
    page: 'https://kenney.nl/assets/interface-sounds',
    preview: '',
    fetch:
      'https://kenney.nl/media/pages/assets/interface-sounds/fa43c1dd4d-1677589452/kenney_interface-sounds.zip',
    member: 'Audio/error_004.ogg',
    author: 'Kenney',
    licence: 'CC0',
    seconds: 0.1,
    why: 'very short error blip',
  },
  {
    slot: 'refused',
    title: 'Interface Sounds / error_006.ogg',
    page: 'https://kenney.nl/assets/interface-sounds',
    preview: '',
    fetch:
      'https://kenney.nl/media/pages/assets/interface-sounds/fa43c1dd4d-1677589452/kenney_interface-sounds.zip',
    member: 'Audio/error_006.ogg',
    author: 'Kenney',
    licence: 'CC0',
    seconds: 0.5,
    why: 'longer, more noticeable error',
  },
  {
    slot: 'alert',
    title: 'Interface Sounds / question_001.ogg',
    page: 'https://kenney.nl/assets/interface-sounds',
    preview: '',
    fetch:
      'https://kenney.nl/media/pages/assets/interface-sounds/fa43c1dd4d-1677589452/kenney_interface-sounds.zip',
    member: 'Audio/question_001.ogg',
    author: 'Kenney',
    licence: 'CC0',
    seconds: 0.49,
    why: 'loud, longer attention cue without being an error buzz',
  },
  {
    slot: 'alert',
    title: 'Interface Sounds / bong_001.ogg',
    page: 'https://kenney.nl/assets/interface-sounds',
    preview: '',
    fetch:
      'https://kenney.nl/media/pages/assets/interface-sounds/fa43c1dd4d-1677589452/kenney_interface-sounds.zip',
    member: 'Audio/bong_001.ogg',
    author: 'Kenney',
    licence: 'CC0',
    seconds: 0.12,
    why: 'single bong, attention-grabbing',
  },
  {
    slot: 'alert',
    title: 'Interface Sounds / error_003.ogg',
    page: 'https://kenney.nl/assets/interface-sounds',
    preview: '',
    fetch:
      'https://kenney.nl/media/pages/assets/interface-sounds/fa43c1dd4d-1677589452/kenney_interface-sounds.zip',
    member: 'Audio/error_003.ogg',
    author: 'Kenney',
    licence: 'CC0',
    seconds: 0.53,
    why: 'longer error tone, more urgent',
  },
  {
    slot: 'notice',
    title: 'Interface Sounds / glass_001.ogg',
    page: 'https://kenney.nl/assets/interface-sounds',
    preview: '',
    fetch:
      'https://kenney.nl/media/pages/assets/interface-sounds/fa43c1dd4d-1677589452/kenney_interface-sounds.zip',
    member: 'Audio/glass_001.ogg',
    author: 'Kenney',
    licence: 'CC0',
    seconds: 0.28,
    why: 'soft glassy ping, quieter than alert',
  },
  {
    slot: 'notice',
    title: 'Interface Sounds / question_002.ogg',
    page: 'https://kenney.nl/assets/interface-sounds',
    preview: '',
    fetch:
      'https://kenney.nl/media/pages/assets/interface-sounds/fa43c1dd4d-1677589452/kenney_interface-sounds.zip',
    member: 'Audio/question_002.ogg',
    author: 'Kenney',
    licence: 'CC0',
    seconds: 0.33,
    why: 'shorter question chime',
  },
  {
    slot: 'notice',
    title: 'Interface Sounds / pluck_002.ogg',
    page: 'https://kenney.nl/assets/interface-sounds',
    preview: '',
    fetch:
      'https://kenney.nl/media/pages/assets/interface-sounds/fa43c1dd4d-1677589452/kenney_interface-sounds.zip',
    member: 'Audio/pluck_002.ogg',
    author: 'Kenney',
    licence: 'CC0',
    seconds: 0.16,
    why: 'gentle pluck',
  },
];
