// '#' paints in the text colour, so the monochrome glyphs follow a button's hover and pressed states.
export const INKS: { readonly [ink: string]: string } = {
  '#': 'currentColor',
  Y: '#fff0a6',
  y: '#f5c03c',
  o: '#e98a2c',
  r: '#d2503a',
  w: '#f3f5f8',
  g: '#c6ceda',
  s: '#8e9aab',
  d: '#6c7686',
  D: '#4a5261',
  b: '#3f8fd8',
  c: '#9fd3f5',
  t: '#c65d36',
  T: '#f4e4cc',
  n: '#7c5232',
  N: '#b98352',
  M: '#d7dde4',
  m: '#98a2ae',
  k: '#4b3a2c',
  l: '#86b34a',
  L: '#557a2c',
  p: '#eab48b',
  q: '#2f8e9e',
  Q: '#236571',
  S: '#e3c48c',
  P: '#ec8fb0',
};

export const ICONS = {
  clear: [
    '.....yy.....',
    '.y...yy...y.',
    '..y......y..',
    '....YYyy....',
    '...YYyyyy...',
    'yy.Yyyyyo.yy',
    'yy.yyyyyo.yy',
    '...yyyyoo...',
    '....yooo....',
    '..y......y..',
    '.y...yy...y.',
    '.....yy.....',
  ],
  star: [
    '.....yy.....',
    '.....Yy.....',
    '....YYyy....',
    '....Yyyo....',
    'yyyyYyyyyooo',
    '.yyYyyyyyoo.',
    '..yYyyyyoo..',
    '...yyyyyo...',
    '..yyyyyooo..',
    '..yyo..ooo..',
    '.yy......oo.',
    '............',
  ],
  rain: [
    '............',
    '....www.....',
    '...wwwww.ww.',
    '.wwwwwwwwwww',
    'wwwwwwwwwwwg',
    'gwwwwwwwwwgg',
    '.ssssssssss.',
    '............',
    '..b...b...b.',
    '.b...b...b..',
    '...b...b....',
    '..b...b.....',
  ],
  storm: [
    '............',
    '....ddd.....',
    '...ddddd.dd.',
    '.ddddddddddd',
    'dddddddddddD',
    'DdddddddddDD',
    '.DDDDDDDDDD.',
    '......yy....',
    '.b...yy...b.',
    '....yyyy....',
    'b....yy...b.',
    '....yy......',
  ],
  heatwave: [
    '.o...oo...o.',
    '....yyyy....',
    '...yyyyyy...',
    'oo.yyyyyr.oo',
    '...yyyyrr...',
    '....yrrr....',
    '.o...oo...o.',
    '............',
    '.rr..rr..rr.',
    'r..rr..rr..r',
    '.rr..rr..rr.',
    'r..rr..rr..r',
  ],
  forecast: [
    '..n......n..',
    '.tnttttttnt.',
    '.tttttttttt.',
    '.TTTTTTTTTT.',
    '.TkkTkkTkkT.',
    '.TTTTTTTTTT.',
    '.TkkTkkTkkT.',
    '.TTTTTTTTTT.',
    '.TkkTkkTTTT.',
    '.TTTTTTTTTT.',
    '.SSSSSSSSSS.',
    '............',
  ],
  // Lit from the top left like the voxel world, and drawn a size down from the 12px icons.
  paused: [
    '..........',
    '.NNN..NNN.',
    '.Nnk..Nnk.',
    '.Nnk..Nnk.',
    '.Nnk..Nnk.',
    '.Nnk..Nnk.',
    '.Nnk..Nnk.',
    '.Nnk..Nnk.',
    '.Nkk..Nkk.',
    '..........',
  ],
  slow: [
    '..........',
    '..........',
    '...N......',
    '...NN.....',
    '...NnN....',
    '...NnnN...',
    '...Nnk....',
    '...Nk.....',
    '...N......',
    '..........',
  ],
  normal: [
    '..N.......',
    '..NN......',
    '..NnN.....',
    '..NnnN....',
    '..NnnnN...',
    '..Nnnk....',
    '..Nnk.....',
    '..Nk......',
    '..N.......',
    '..........',
  ],
  fast: [
    '..........',
    '..........',
    'N.....N...',
    'NN....NN..',
    'NnN...NnN.',
    'NnnN..NnnN',
    'Nnk...Nnk.',
    'Nk....Nk..',
    'N.....N...',
    '..........',
  ],
  rush: [
    '..........',
    '..........',
    '..........',
    'N..N..N...',
    'NN.NN.NN..',
    'NnNnnNnnN.',
    'Nk.Nk.Nk..',
    'N..N..N...',
    '..........',
    '..........',
  ],
  menu: [
    '..........',
    'NNNNNNNNNN',
    'Nkkkkkkkkk',
    '..........',
    'NNNNNNNNNN',
    'Nkkkkkkkkk',
    '..........',
    'NNNNNNNNNN',
    'Nkkkkkkkkk',
    '..........',
  ],
  close: [
    '............',
    '............',
    '..##....##..',
    '..###..###..',
    '...######...',
    '....####....',
    '....####....',
    '...######...',
    '..###..###..',
    '..##....##..',
    '............',
    '............',
  ],
  sound: [
    '............',
    '.....#......',
    '....##...#..',
    '...###....#.',
    '######.#..#.',
    '######..#..#',
    '######..#..#',
    '######.#..#.',
    '...###....#.',
    '....##...#..',
    '.....#......',
    '............',
  ],
  muted: [
    '............',
    '.....#......',
    '....##......',
    '...###......',
    '######.#...#',
    '######..#.#.',
    '######...#..',
    '######..#.#.',
    '...###.#...#',
    '....##......',
    '.....#......',
    '............',
  ],
  caret: [
    '............',
    '............',
    '............',
    '............',
    '...#....#...',
    '...##..##...',
    '....####....',
    '.....##.....',
    '............',
    '............',
    '............',
    '............',
  ],
  check: [
    '............',
    '............',
    '............',
    '.........##.',
    '........##..',
    '.##....##...',
    '..##..##....',
    '...####.....',
    '....##......',
    '............',
    '............',
    '............',
  ],
  build: [
    '............',
    '..MMMMMMMM..',
    '.mmmmmmmmmm.',
    '..dddddddd..',
    '.....Nn.....',
    '.....Nn.....',
    '.....Nn.....',
    '.....Nn.....',
    '.....Nn.....',
    '.....Nn.....',
    '.....Nn.....',
    '.....nn.....',
  ],
  overview: [
    '............',
    '.......tt...',
    '.......tt...',
    '.......tt...',
    '....yy.tt...',
    '....yy.tt...',
    '....yy.tt...',
    '.ll.yy.tt...',
    '.ll.yy.tt...',
    '.ll.yy.tt...',
    '.ll.yy.tt...',
    'kkkkkkkkkkk.',
  ],
  advice: [
    '....YYyy....',
    '...YYyyyy...',
    '..YYyyyyyo..',
    '..Yyyyyyyo..',
    '..yyyyyyyo..',
    '...yyyyyo...',
    '....yyyo....',
    '....MMMM....',
    '....mmmm....',
    '....MMMM....',
    '....dddd....',
    '.....dd.....',
  ],
  alert: [
    '.....rr.....',
    '.....rr.....',
    '....rrrr....',
    '....rwwr....',
    '...rrwwrr...',
    '...rrwwrr...',
    '..rrrwwrrr..',
    '..rrrwwrrr..',
    '.rrrrrrrrrr.',
    '.rrrrwwrrrr.',
    'rrrrrwwrrrrr',
    'rrrrrrrrrrrr',
  ],
  refresh: [
    '.......b....',
    '...bbbbbb...',
    '..bbbbbbbb..',
    '.bb....bb...',
    '.bb....b....',
    '.bb.........',
    '.bb......bb.',
    '.bb......bb.',
    '..bb....bb..',
    '..bbbbbbbb..',
    '...bbbbbb...',
    '............',
  ],
  rename: [
    '............',
    '........##..',
    '.......####.',
    '......####..',
    '.....####...',
    '....####....',
    '...####.....',
    '..####......',
    '..###.......',
    '..##........',
    '............',
    '............',
  ],
  guests: [
    '............',
    '....nnnn....',
    '...nppppn...',
    '....pppp....',
    '....pppp....',
    '.....pp.....',
    '..qqqqqqqq..',
    '.qqqqqqqqqq.',
    '.qqqqqqqqqq.',
    '.pqqqqqqqqp.',
    '..QQQQQQQQ..',
    '...QQ..QQ...',
  ],
  inbox: [
    '............',
    '............',
    'dddddddddddd',
    'dsgwwwwwwgsd',
    'dwsgwwwwgswd',
    'dwwsgwwgswwd',
    'dwwwsggswwwd',
    'dwwwwsswwwwd',
    'dwwwwwwwwwwd',
    'dggggggggggd',
    'dddddddddddd',
    '............',
  ],
  messages: [
    '............',
    '.ssssssssss.',
    'swwwwwwwwwws',
    'swwwwwwwwwws',
    'swDDwDDwDDws',
    'swDDwDDwDDws',
    'swwwwwwwwwws',
    'sggggggggggs',
    '.sgssssssss.',
    '.sgs........',
    '.ss.........',
    '............',
  ],
  people: [
    '.......nnnn.',
    '.......pppp.',
    '.......pppp.',
    '..nnnn..pp..',
    '..pppp.QQQQQ',
    '..pppp.QQQQQ',
    '...pp.QQQQQQ',
    '.qqqqqqQQQQQ',
    'qqqqqqqqQQQQ',
    'pqqqqqqpQQQQ',
    '.qqqqqq.QQQQ',
    '.QQ..QQ..QQ.',
  ],
  staff: [
    '....bbbb....',
    '...bbbbbb...',
    '...bbbbbbbb.',
    '....pppp....',
    '....pppp....',
    '.....pp.....',
    '..bbbbbbbb..',
    '.bbbbbbyybb.',
    '.bbbbbbyybb.',
    '.pbbbbbbbbp.',
    '..bbbbbbbb..',
    '...nn..nn...',
  ],
  report: [
    '....ssss....',
    '.NNsddddsNN.',
    '.NwwwwwwwwN.',
    '.NwsssssswN.',
    '.NwwwwwwwwN.',
    '.NwsssssswN.',
    '.NwwwwwwwwN.',
    '.NwssssswwN.',
    '.NwwwwwwwwN.',
    '.NwwwwwwwwN.',
    '.NNNNNNNNNN.',
    '.nnnnnnnnnn.',
  ],
  demand: [
    '.....lL.....',
    '....llLL....',
    '...lllLLL...',
    '..llllLLLL..',
    '....llLL....',
    '....llLL....',
    '....llLL....',
    '.yyyyyyyyoo.',
    '.yyyyyyyyoo.',
    '.yyyyyyyyoo.',
    '.yyyyyyyyoo.',
    '.oooooooooo.',
  ],
  inspect: [
    '...####.....',
    '..#cccc#....',
    '.#cwwccc#...',
    '.#cwcccc#...',
    '.#cccccc#...',
    '.#cccccc#...',
    '..#cccc#....',
    '...####ss...',
    '........##..',
    '.........##.',
    '..........##',
    '............',
  ],
  saves: [
    'bbbbbbbbbb..',
    'bbccccDcbbb.',
    'bbccccDcbbbb',
    'bbccccccbbbb',
    'bbbbbbbbbbbb',
    'bbbbbbbbbbbb',
    'bwwwwwwwwwwb',
    'bwDDDDDDDDwb',
    'bwwwwwwwwwwb',
    'bwDDDDDDwwwb',
    'bwwwwwwwwwwb',
    'bbbbbbbbbbbb',
  ],
  books: [
    '............',
    '...YYYYYY...',
    '..yyyyyyyy..',
    '..oooooooo..',
    '...YYYYYY...',
    '..yyyyyyyy..',
    '..oooooooo..',
    '...YYYYYY...',
    '..yyyyyyyy..',
    '..oooooooo..',
    '............',
    '............',
  ],
  camera: [
    '............',
    '............',
    '..ddd.......',
    '.dddddddddd.',
    '.dmmkkkkmyd.',
    '.dmkbcbbkmd.',
    '.dmkbbbbkmd.',
    '.dmmkkkkmmd.',
    '.dddddddddd.',
    '............',
    '............',
    '............',
  ],
  resort: [
    '............',
    '....tTTt....',
    '...ttTTtt...',
    '..tttTTttt..',
    '.ttttTTtttt.',
    '.....nn.....',
    '.....nn.....',
    '.....nn.....',
    '.....nn.....',
    '.....nn.....',
    '.SSSSSSSSSS.',
    '............',
  ],
  debug: [
    '...n....n...',
    '....n..n....',
    '....nnnn....',
    '...llLLll...',
    '.nnllLLllnn.',
    '...llLLll...',
    '.nnllLLllnn.',
    '...llLLll...',
    '.nnllLLllnn.',
    '...llLLll...',
    '....llll....',
    '............',
  ],
  overlay: [
    '............',
    '.....ll.....',
    '...llllll...',
    '.llllllllll.',
    '...llllll...',
    '.bb..ll..bb.',
    '...bbbbbb...',
    '.tt..bb..tt.',
    '...tttttt...',
    '.....tt.....',
    '............',
    '............',
  ],
  broken: [
    '........g..g',
    '.......gs..s',
    '.......gsgss',
    '......gsss..',
    '.....gss....',
    '....gss.....',
    '...gss......',
    '..gss.......',
    '.gss........',
    'gss.........',
    'ss..........',
    '............',
  ],
  stranded: [
    '...rrrrrr...',
    '..rrrrrrrr..',
    '.rrrrrrrrrr.',
    'rrrrrrrrrrrr',
    'rrrrrrrrrrrr',
    'rwwwwwwwwwwr',
    'rwwwwwwwwwwr',
    'rrrrrrrrrrrr',
    'rrrrrrrrrrrr',
    '.rrrrrrrrrr.',
    '..rrrrrrrr..',
    '...rrrrrr...',
  ],
  wheelchair: [
    '.....bb.....',
    '.....bb.....',
    '......b.....',
    '......bbbb..',
    '......b.....',
    '...bb.bbbbb.',
    '..b...b...b.',
    '.b........b.',
    '.b......b.bb',
    '.b......b...',
    '..b....b....',
    '...bbbb.....',
  ],
  queue: [
    '............',
    '............',
    '.nn..nn..nn.',
    '.pp..pp..pp.',
    '.pp..pp..pp.',
    'qqqqbbbbtttt',
    'qqqqbbbbtttt',
    'qqqqbbbbtttt',
    '.dd..dd..dd.',
    '.dd..dd..dd.',
    '............',
    '............',
  ],
  dirty: [
    '.....d...d..',
    '..d.........',
    '............',
    '....nn......',
    '..nnNNnn....',
    '.nNNNNNNn.n.',
    'nNNNNNNNNn..',
    '.nNNNNNNNNn.',
    '..nNNNNNn...',
    '...nn.nn....',
    '.n..........',
    '............',
  ],
  lifeguard: [
    '....rrrr....',
    '..rrrrrrrr..',
    '.wwrr..rrww.',
    '.www....www.',
    'www......www',
    'www......www',
    'www......www',
    'www......www',
    '.www....www.',
    '.wwrr..rrww.',
    '..rrrrrrrr..',
    '....rrrr....',
  ],
  litter: [
    '............',
    '......k.....',
    '.....yy.....',
    '....Yyyo....',
    '....Yyyo....',
    '...YyYyoo...',
    '..Yy.Yy.yo..',
    '..Yy.Yy.yo..',
    '.Yy..Yy..yo.',
    '.y...yo...o.',
    '............',
    '............',
  ],
  // The staff pins: each role's cap and shirt, as the figures wear them.
  cleaner: [
    '..qqqq..',
    '.qqqqqq.',
    '..pppp..',
    '..pppp..',
    '.wwwwww.',
    'pwwwwwwp',
    '.wwwwww.',
    '.DD..DD.',
  ],
  guard: [
    '..rrrr..',
    '.rrrrrr.',
    '..pppp..',
    '..pppp..',
    '.yyyyyy.',
    'pyyyyyyp',
    '.yyyyyy.',
    '.rr..rr.',
  ],
  animator: [
    '..YYYY..',
    '.YYYYYY.',
    '..pppp..',
    '..pppp..',
    '.rrrrrr.',
    'prrrrrrp',
    '.rrrrrr.',
    '.bb..bb.',
  ],
  mechanic: [
    '..DDDD..',
    '.DDDDDD.',
    '..pppp..',
    '..pppp..',
    '.tttttt.',
    'pttttttp',
    '.tttttt.',
    '.tt..tt.',
  ],
  // The venue signs: what kind of place stands under each, as a shop sign would say.
  restaurant: [
    '..d.d.d..m..',
    '..d.d.d..mm.',
    '..d.d.d..mm.',
    '..d.d.d..mm.',
    '..ddddd..mm.',
    '...ddd...mm.',
    '....d....md.',
    '....d....d..',
    '....d....d..',
    '....d....d..',
    '....d....d..',
    '....d....d..',
  ],
  bakery: [
    '............',
    '............',
    '....NNNN....',
    '..NNNNNNNN..',
    '.NNTNNTNNTN.',
    'NNNNTNNTNNTN',
    'NNNNNNNNNNNN',
    'nNNNNNNNNNNn',
    'nnNNNNNNNNnn',
    '.nnnnnnnnnn.',
    '............',
    '............',
  ],
  icecream: [
    '....PPPP....',
    '...PPPPPP...',
    '..PPwPPPPP..',
    '..PPPPPPPP..',
    '..TTTTTTTT..',
    '...NnNnNnN..',
    '...nNnNnN...',
    '....NnNnN...',
    '....nNnN....',
    '.....NnN....',
    '.....nN.....',
    '......n.....',
  ],
  snack: [
    '............',
    '...NNNNNN...',
    '..NNTNNTNN..',
    '.NNNNNNNNNN.',
    '.llllllllll.',
    '.rrrrrrrrrr.',
    '.kkkkkkkkkk.',
    '.kkkkkkkkkk.',
    '.yyyyyyyyyy.',
    '.NNNNNNNNNN.',
    '..nnnnnnnn..',
    '............',
  ],
  shop: [
    '............',
    '...kkkkkk...',
    '..k......k..',
    '..k.rryl.k..',
    '.nnnnnnnnnn.',
    '.nNnNnNnNnN.',
    '..NnNnNnNn..',
    '..nNnNnNnN..',
    '..NnNnNnNn..',
    '...nnnnnn...',
    '............',
    '............',
  ],
  coffee: [
    '...s..s.....',
    '....s..s....',
    '...s..s.....',
    '............',
    '.ttttttttt..',
    '.tttttttttt.',
    '.ttttttttt.t',
    '.ttttttttt.t',
    '.tttttttttt.',
    '..ttttttt...',
    '.ddddddddd..',
    '............',
  ],
  bar: [
    '.......l....',
    '......l.....',
    'scccccLcccss',
    '.sccccccccs.',
    '..sccccccs..',
    '...sccccs...',
    '....sccs....',
    '.....ss.....',
    '.....ss.....',
    '.....ss.....',
    '...ssssss...',
    '............',
  ],
  toilets: [
    '............',
    '............',
    '.b...b..bbb.',
    '.b...b.b....',
    '.b...b.b....',
    '.b.b.b.b....',
    '.b.b.b.b....',
    '.bb.bb.b....',
    '.b...b..bbb.',
    '............',
    '............',
    '............',
  ],
  shower: [
    '.....ss.....',
    '.....ss.....',
    '....ssss....',
    '..mmmmmmmm..',
    '.mmmmmmmmmm.',
    '............',
    '..b.b..b.b..',
    '.b..b..b..b.',
    '..b.b..b.b..',
    '.b..b..b..b.',
    '............',
    '............',
  ],
  cabins: [
    '.....ss.....',
    '....s..s....',
    '.......s....',
    '......s.....',
    '.....nn.....',
    '....nnnn....',
    '...nn..nn...',
    '..nn....nn..',
    '.nn......nn.',
    'nnnnnnnnnnnn',
    '............',
    '............',
  ],
  'first-aid': [
    '............',
    '....rrrr....',
    '....rrrr....',
    '....rrrr....',
    '.rrrrrrrrrr.',
    '.rrrrrrrrrr.',
    '.rrrrrrrrrr.',
    '.rrrrrrrrrr.',
    '....rrrr....',
    '....rrrr....',
    '....rrrr....',
    '............',
  ],
  reception: [
    '............',
    '.....yy.....',
    '.....yy.....',
    '....YYyy....',
    '...YYyyyy...',
    '..YYyyyyyo..',
    '..Yyyyyyyo..',
    '.Yyyyyyyyyo.',
    '.yyyyyyyyyo.',
    'oooooooooooo',
    'dddddddddddd',
    '............',
  ],
  stage: [
    '............',
    '....DDDDDD..',
    '....D....D..',
    '....D....D..',
    '....D....D..',
    '..DDD..DDD..',
    '..DDD..DDD..',
    '............',
    'yyyyyyyyyyyy',
    'NNNNNNNNNNNN',
    'n.n......n.n',
    'n.n......n.n',
  ],
  programme: [
    '.....yy.....',
    '.....Yy.....',
    '..yyYYyyyo..',
    '...yYyyyo...',
    '....yyyo....',
    '...yyo.yo...',
    '..yo.....o..',
    '............',
    'yyyyyyyyyyyy',
    'NNNNNNNNNNNN',
    'n.n......n.n',
    'n.n......n.n',
  ],
  club: [
    '............',
    '.....ry.....',
    '...rrryyy...',
    '..rrrryyyy..',
    '.rrrrryyyyy.',
    'rrrrrryyyyyy',
    '.....n......',
    '.....n......',
    '.....n......',
    '.....n......',
    '.....n......',
    'SSSSSSSSSSSS',
  ],
  games: [
    '............',
    '.....rr.....',
    '....rrrr....',
    '....rrrr....',
    '.....rr.....',
    '.....dd.....',
    '.....dd.....',
    '.yy..dd.....',
    'DDDDDDDDDDDD',
    'DddddddddddD',
    'DDDDDDDDDDDD',
    '............',
  ],
  gym: [
    '............',
    '............',
    '............',
    '.DD......DD.',
    'DDD......DDD',
    'DDDssssssDDD',
    'DDDssssssDDD',
    'DDD......DDD',
    '.DD......DD.',
    '............',
    '............',
    '............',
  ],
  spa: [
    '............',
    '.....PP.....',
    '....PPPP....',
    '....PPPP....',
    '.P..PPPP..P.',
    '.PP.PPPP.PP.',
    '.PPPPPPPPPP.',
    '..PPPPPPPP..',
    '...PPPPPP...',
    '.LLLLLLLLLL.',
    '..LLLLLLLL..',
    '............',
  ],
  kids: [
    '.NN......NN.',
    '.NNNNNNNNNN.',
    '..NkNNNNkN..',
    '..NNNkkNNN..',
    '...NNNNNN...',
    '..nNNNNNNn..',
    '.nnNTTTTNnn.',
    '.nnNTTTTNnn.',
    '...NTTTTN...',
    '..NNN..NNN..',
    '..NNN..NNN..',
    '............',
  ],
  playground: [
    '.s..s.......',
    '.ssss.......',
    '.s..sy......',
    '.ssssyy.....',
    '.s..s.yy....',
    '.ssss..yy...',
    '.s..s...yy..',
    '.ssss....yy.',
    '.s..s.....yy',
    '.s..s......y',
    'llllllllllll',
    '............',
  ],
  boats: [
    '............',
    '............',
    '...yyyyyy...',
    '...y....y...',
    '...y....y...',
    '.tttttttttt.',
    'tttttttttttt',
    '.mmmmmmmmmm.',
    '..mm....mm..',
    'cbbcbbcbbcbb',
    'bbcbbcbbcbbc',
    '............',
  ],
  golf: [
    '.....rrr....',
    '.....rrrrr..',
    '.....rrr....',
    '.....d......',
    '.....d......',
    '.....d......',
    '.....d......',
    '.....d......',
    '.llllklllll.',
    'llllllllllll',
    '.LLLLLLLLLL.',
    '............',
  ],
  pool: [
    '..mm...mm...',
    '....m....m..',
    '....m....m..',
    '....mmmmmm..',
    '....m....m..',
    '....mmmmmm..',
    '....m....m..',
    'bbbbmbbbbmbb',
    'cbbcbbcbbcbb',
    'bbbbbbbbbbbb',
    'bcbbcbbcbbcb',
    '............',
  ],
  waterpark: [
    '.qq.........',
    '.qqqq.......',
    '...qqqq.....',
    '.....qqq....',
    '......qq....',
    '.....qqq....',
    '...qqqq.....',
    '..qqq.......',
    '..qqqq......',
    '....qqqqq...',
    'bbcbbcbbcqqb',
    'cbbcbbcbbcbb',
  ],
  tennis: [
    '..ssss...ll.',
    '.sMsMss..ll.',
    'sMsMsMss....',
    'ssMsMsMs....',
    'sMsMsMss....',
    'ssMsMsMs....',
    '.ssMsMs.....',
    '..ssssn.....',
    '......nn....',
    '.......nn...',
    '........nn..',
    '.........nn.',
  ],
  basketball: [
    '.MMMMMMMMMM.',
    '.M..rrrr..M.',
    '.M..r..r..M.',
    '.MMMMMMMMMM.',
    '...oooooo...',
    '...s.ss.s...',
    '....s..s....',
    '....ssss....',
    '.....ss.....',
    '....oooo....',
    '....oooo....',
    '............',
  ],
  volleyball: [
    '....bbbb....',
    '..bbYYYYbb..',
    '.bYYYbbYYYb.',
    '.bYYbYYbYYb.',
    'bYYbYYYYbYYb',
    'bYbYYYYYYbYb',
    'bYbYYYYYYbYb',
    'bYYbYYYYbYYb',
    '.bYYbbbbYYb.',
    '.bYYYYYYYYb.',
    '..bbYYYYbb..',
    '....bbbb....',
  ],
  nightclub: [
    '.....D......',
    '.....D......',
    '....cwc.....',
    '...cwcwc....',
    '...wcwcw....',
    '....cwc.....',
    '............',
    '..PP....PP..',
    '..P.P...P.P.',
    '..P.....P...',
    '.PP....PP...',
    '.PP....PP...',
  ],
  bonfire: [
    '............',
    '.....y......',
    '....yy......',
    '....yoy.....',
    '...yoooy....',
    '...yorroy...',
    '..yorrrroy..',
    '..yorrrroy..',
    '...nNNNNn...',
    '.nNNn..nNNn.',
    'nNn......nNn',
    '............',
  ],
  watersports: [
    '............',
    '............',
    '......D.....',
    '.....DD.....',
    '..rrrrrrr...',
    '.rrrrrrrrrr.',
    '..wwwwwwwww.',
    '............',
    '.c..c..c..c.',
    'cbbcbbcbbcbb',
    'bbcbbcbbcbbc',
    '............',
  ],
} as const satisfies { readonly [name: string]: readonly string[] };

export type IconName = keyof typeof ICONS;
