// '#' paints in the text colour, so the monochrome glyphs follow a button's hover and pressed states.
export const INKS: { readonly [ink: string]: string } = {
  '#': 'currentColor',
  Y: '#fff0a6',
  y: '#f5c03c',
  o: '#e98a2c',
  r: '#d2503a',
  w: '#f3f5f8',
  g: '#c6ceda',
  s: '#8e9aab',
  d: '#6c7686',
  D: '#4a5261',
  b: '#3f8fd8',
  c: '#9fd3f5',
  t: '#c65d36',
  T: '#f4e4cc',
  n: '#7c5232',
  N: '#b98352',
  M: '#d7dde4',
  m: '#98a2ae',
  k: '#4b3a2c',
  l: '#86b34a',
  L: '#557a2c',
  p: '#eab48b',
  q: '#2f8e9e',
  Q: '#236571',
  S: '#e3c48c',
};

export const ICONS = {
  clear: [
    '.....yy.....',
    '.y...yy...y.',
    '..y......y..',
    '....YYyy....',
    '...YYyyyy...',
    'yy.Yyyyyo.yy',
    'yy.yyyyyo.yy',
    '...yyyyoo...',
    '....yooo....',
    '..y......y..',
    '.y...yy...y.',
    '.....yy.....',
  ],
  star: [
    '.....yy.....',
    '.....Yy.....',
    '....YYyy....',
    '....Yyyo....',
    'yyyyYyyyyooo',
    '.yyYyyyyyoo.',
    '..yYyyyyoo..',
    '...yyyyyo...',
    '..yyyyyooo..',
    '..yyo..ooo..',
    '.yy......oo.',
    '............',
  ],
  rain: [
    '............',
    '....www.....',
    '...wwwww.ww.',
    '.wwwwwwwwwww',
    'wwwwwwwwwwwg',
    'gwwwwwwwwwgg',
    '.ssssssssss.',
    '............',
    '..b...b...b.',
    '.b...b...b..',
    '...b...b....',
    '..b...b.....',
  ],
  storm: [
    '............',
    '....ddd.....',
    '...ddddd.dd.',
    '.ddddddddddd',
    'dddddddddddD',
    'DdddddddddDD',
    '.DDDDDDDDDD.',
    '......yy....',
    '.b...yy...b.',
    '....yyyy....',
    'b....yy...b.',
    '....yy......',
  ],
  heatwave: [
    '.o...oo...o.',
    '....yyyy....',
    '...yyyyyy...',
    'oo.yyyyyr.oo',
    '...yyyyrr...',
    '....yrrr....',
    '.o...oo...o.',
    '............',
    '.rr..rr..rr.',
    'r..rr..rr..r',
    '.rr..rr..rr.',
    'r..rr..rr..r',
  ],
  forecast: [
    '..n......n..',
    '.tnttttttnt.',
    '.tttttttttt.',
    '.TTTTTTTTTT.',
    '.TkkTkkTkkT.',
    '.TTTTTTTTTT.',
    '.TkkTkkTkkT.',
    '.TTTTTTTTTT.',
    '.TkkTkkTTTT.',
    '.TTTTTTTTTT.',
    '.SSSSSSSSSS.',
    '............',
  ],
  paused: [
    '............',
    '............',
    '...##..##...',
    '...##..##...',
    '...##..##...',
    '...##..##...',
    '...##..##...',
    '...##..##...',
    '...##..##...',
    '...##..##...',
    '............',
    '............',
  ],
  slow: [
    '............',
    '............',
    '............',
    '....#.......',
    '....##......',
    '....###.....',
    '....###.....',
    '....##......',
    '....#.......',
    '............',
    '............',
    '............',
  ],
  normal: [
    '............',
    '...#........',
    '...##.......',
    '...###......',
    '...####.....',
    '...#####....',
    '...#####....',
    '...####.....',
    '...###......',
    '...##.......',
    '...#........',
    '............',
  ],
  fast: [
    '............',
    '............',
    '.#....#.....',
    '.##...##....',
    '.###..###...',
    '.####.####..',
    '.####.####..',
    '.###..###...',
    '.##...##....',
    '.#....#.....',
    '............',
    '............',
  ],
  rush: [
    '............',
    '............',
    '............',
    '#...#...#...',
    '##..##..##..',
    '###.###.###.',
    '###.###.###.',
    '##..##..##..',
    '#...#...#...',
    '............',
    '............',
    '............',
  ],
  menu: [
    '............',
    '............',
    '..########..',
    '..########..',
    '............',
    '..########..',
    '..########..',
    '............',
    '..########..',
    '..########..',
    '............',
    '............',
  ],
  close: [
    '............',
    '............',
    '..##....##..',
    '..###..###..',
    '...######...',
    '....####....',
    '....####....',
    '...######...',
    '..###..###..',
    '..##....##..',
    '............',
    '............',
  ],
  caret: [
    '............',
    '............',
    '............',
    '............',
    '...#....#...',
    '...##..##...',
    '....####....',
    '.....##.....',
    '............',
    '............',
    '............',
    '............',
  ],
  check: [
    '............',
    '............',
    '............',
    '.........##.',
    '........##..',
    '.##....##...',
    '..##..##....',
    '...####.....',
    '....##......',
    '............',
    '............',
    '............',
  ],
  build: [
    '............',
    '..MMMMMMMM..',
    '.mmmmmmmmmm.',
    '..dddddddd..',
    '.....Nn.....',
    '.....Nn.....',
    '.....Nn.....',
    '.....Nn.....',
    '.....Nn.....',
    '.....Nn.....',
    '.....Nn.....',
    '.....nn.....',
  ],
  overview: [
    '............',
    '.......tt...',
    '.......tt...',
    '.......tt...',
    '....yy.tt...',
    '....yy.tt...',
    '....yy.tt...',
    '.ll.yy.tt...',
    '.ll.yy.tt...',
    '.ll.yy.tt...',
    '.ll.yy.tt...',
    'kkkkkkkkkkk.',
  ],
  advice: [
    '....YYyy....',
    '...YYyyyy...',
    '..YYyyyyyo..',
    '..Yyyyyyyo..',
    '..yyyyyyyo..',
    '...yyyyyo...',
    '....yyyo....',
    '....MMMM....',
    '....mmmm....',
    '....MMMM....',
    '....dddd....',
    '.....dd.....',
  ],
  alert: [
    '.....rr.....',
    '.....rr.....',
    '....rrrr....',
    '....rwwr....',
    '...rrwwrr...',
    '...rrwwrr...',
    '..rrrwwrrr..',
    '..rrrwwrrr..',
    '.rrrrrrrrrr.',
    '.rrrrwwrrrr.',
    'rrrrrwwrrrrr',
    'rrrrrrrrrrrr',
  ],
  guests: [
    '............',
    '....nnnn....',
    '...nppppn...',
    '....pppp....',
    '....pppp....',
    '.....pp.....',
    '..qqqqqqqq..',
    '.qqqqqqqqqq.',
    '.qqqqqqqqqq.',
    '.pqqqqqqqqp.',
    '..QQQQQQQQ..',
    '...QQ..QQ...',
  ],
  books: [
    '............',
    '...YYYYYY...',
    '..yyyyyyyy..',
    '..oooooooo..',
    '...YYYYYY...',
    '..yyyyyyyy..',
    '..oooooooo..',
    '...YYYYYY...',
    '..yyyyyyyy..',
    '..oooooooo..',
    '............',
    '............',
  ],
  camera: [
    '............',
    '............',
    '..ddd.......',
    '.dddddddddd.',
    '.dmmkkkkmyd.',
    '.dmkbcbbkmd.',
    '.dmkbbbbkmd.',
    '.dmmkkkkmmd.',
    '.dddddddddd.',
    '............',
    '............',
    '............',
  ],
  resort: [
    '............',
    '....tTTt....',
    '...ttTTtt...',
    '..tttTTttt..',
    '.ttttTTtttt.',
    '.....nn.....',
    '.....nn.....',
    '.....nn.....',
    '.....nn.....',
    '.....nn.....',
    '.SSSSSSSSSS.',
    '............',
  ],
  debug: [
    '...n....n...',
    '....n..n....',
    '....nnnn....',
    '...llLLll...',
    '.nnllLLllnn.',
    '...llLLll...',
    '.nnllLLllnn.',
    '...llLLll...',
    '.nnllLLllnn.',
    '...llLLll...',
    '....llll....',
    '............',
  ],
  overlay: [
    '............',
    '.....ll.....',
    '...llllll...',
    '.llllllllll.',
    '...llllll...',
    '.bb..ll..bb.',
    '...bbbbbb...',
    '.tt..bb..tt.',
    '...tttttt...',
    '.....tt.....',
    '............',
    '............',
  ],
  broken: [
    '........g..g',
    '.......gs..s',
    '.......gsgss',
    '......gsss..',
    '.....gss....',
    '....gss.....',
    '...gss......',
    '..gss.......',
    '.gss........',
    'gss.........',
    'ss..........',
    '............',
  ],
  stranded: [
    '...rrrrrr...',
    '..rrrrrrrr..',
    '.rrrrrrrrrr.',
    'rrrrrrrrrrrr',
    'rrrrrrrrrrrr',
    'rwwwwwwwwwwr',
    'rwwwwwwwwwwr',
    'rrrrrrrrrrrr',
    'rrrrrrrrrrrr',
    '.rrrrrrrrrr.',
    '..rrrrrrrr..',
    '...rrrrrr...',
  ],
  wheelchair: [
    '.....bb.....',
    '.....bb.....',
    '......b.....',
    '......bbbb..',
    '......b.....',
    '...bb.bbbbb.',
    '..b...b...b.',
    '.b........b.',
    '.b......b.bb',
    '.b......b...',
    '..b....b....',
    '...bbbb.....',
  ],
  queue: [
    '............',
    '............',
    '.nn..nn..nn.',
    '.pp..pp..pp.',
    '.pp..pp..pp.',
    'qqqqbbbbtttt',
    'qqqqbbbbtttt',
    'qqqqbbbbtttt',
    '.dd..dd..dd.',
    '.dd..dd..dd.',
    '............',
    '............',
  ],
  dirty: [
    '.....d...d..',
    '..d.........',
    '............',
    '....nn......',
    '..nnNNnn....',
    '.nNNNNNNn.n.',
    'nNNNNNNNNn..',
    '.nNNNNNNNNn.',
    '..nNNNNNn...',
    '...nn.nn....',
    '.n..........',
    '............',
  ],
  lifeguard: [
    '....rrrr....',
    '..rrrrrrrr..',
    '.wwrr..rrww.',
    '.www....www.',
    'www......www',
    'www......www',
    'www......www',
    'www......www',
    '.www....www.',
    '.wwrr..rrww.',
    '..rrrrrrrr..',
    '....rrrr....',
  ],
  litter: [
    '............',
    '......k.....',
    '.....yy.....',
    '....Yyyo....',
    '....Yyyo....',
    '...YyYyoo...',
    '..Yy.Yy.yo..',
    '..Yy.Yy.yo..',
    '.Yy..Yy..yo.',
    '.y...yo...o.',
    '............',
    '............',
  ],
  // The staff pins: each role's cap and shirt, as the figures wear them.
  cleaner: [
    '..qqqq..',
    '.qqqqqq.',
    '..pppp..',
    '..pppp..',
    '.wwwwww.',
    'pwwwwwwp',
    '.wwwwww.',
    '.DD..DD.',
  ],
  guard: [
    '..rrrr..',
    '.rrrrrr.',
    '..pppp..',
    '..pppp..',
    '.yyyyyy.',
    'pyyyyyyp',
    '.yyyyyy.',
    '.rr..rr.',
  ],
  animator: [
    '..YYYY..',
    '.YYYYYY.',
    '..pppp..',
    '..pppp..',
    '.rrrrrr.',
    'prrrrrrp',
    '.rrrrrr.',
    '.bb..bb.',
  ],
  mechanic: [
    '..DDDD..',
    '.DDDDDD.',
    '..pppp..',
    '..pppp..',
    '.tttttt.',
    'pttttttp',
    '.tttttt.',
    '.tt..tt.',
  ],
} as const satisfies { readonly [name: string]: readonly string[] };

export type IconName = keyof typeof ICONS;
