/**
 * What the guests are called.
 *
 * Two lists and a draw, and that is the whole module - but the lists are worth
 * some care, because a name is the first thing anybody will read about a guest
 * and a resort of Smiths and Joneses reads as placeholder text. The resort is
 * Mediterranean: `docs/art-direction.md` builds it out of tavernas, whitewash,
 * olives and cypresses, so the names are drawn from the same coast.
 *
 * Family names and given names are drawn separately, so a party of five is one
 * surname and five given names rather than five unrelated people.
 */

/** Given names an adult guest may have. */
export const GIVEN_NAMES: readonly string[] = [
  'Elena',
  'Marco',
  'Sofia',
  'Giorgos',
  'Lucía',
  'Andreas',
  'Chiara',
  'Javier',
  'Maria',
  'Nikos',
  'Francesca',
  'Pau',
  'Ana',
  'Emre',
  'Ivana',
  'Luca',
  'Carmen',
  'Dimitris',
  'Giulia',
  'João',
  'Ayşe',
  'Tomislav',
  'Montserrat',
  'Alessandro',
  'Katerina',
  'Rafael',
  'Beatriz',
  'Mehmet',
  'Ines',
  'Stefano',
  'Eleni',
  'Jordi',
  'Marija',
  'Paolo',
  'Pilar',
  'Kostas',
  'Valentina',
  'Miguel',
  'Zeynep',
  'Ante',
  'Núria',
  'Vasiliki',
  'Lorenzo',
  'Teresa',
  'Burak',
  'Luka',
  'Rosa',
  'Yannis',
  'Federica',
  'Diego',
  'Leonor',
  'Selin',
  'Petra',
  'Matteo',
  'Mercè',
  'Spyros',
  'Isabel',
  'Duarte',
  'Elif',
  'Davor',
  'Anna',
  'Xavier',
  'Despina',
  'Riccardo',
  'Catarina',
  'Cem',
];

/** Given names a child guest may have; a shorter list, deliberately. */
export const CHILD_NAMES: readonly string[] = [
  'Nico',
  'Martina',
  'Pablo',
  'Eva',
  'Stavros',
  'Aurora',
  'Arda',
  'Mateo',
  'Lana',
  'Tiago',
  'Irene',
  'Pol',
  'Emma',
  'Filippo',
  'Defne',
  'Leo',
  'Clara',
  'Alexis',
  'Bruna',
  'Marc',
  'Ela',
  'Tommaso',
  'Nerea',
  'Ivan',
  'Myrto',
  'Gonçalo',
  'Alba',
  'Kerem',
  'Mia',
  'Enzo',
  'Daria',
  'Rui',
];

/** Family names a party may share. */
export const FAMILY_NAMES: readonly string[] = [
  'Marchetti',
  'Papadopoulos',
  'García',
  'Puig',
  'Silva',
  'Yılmaz',
  'Horvat',
  'Rossi',
  'Georgiou',
  'Fernández',
  'Ferrer',
  'Costa',
  'Kaya',
  'Kovačević',
  'Bianchi',
  'Nikolaidis',
  'Moreno',
  'Vidal',
  'Pereira',
  'Demir',
  'Babić',
  'Esposito',
  'Christodoulou',
  'Ruiz',
  'Soler',
  'Oliveira',
  'Şahin',
  'Jurić',
  'Romano',
  'Alexiou',
  'Navarro',
  'Casals',
  'Santos',
  'Çelik',
  'Marić',
  'Colombo',
  'Karagiannis',
  'Ortega',
  'Roca',
  'Carvalho',
  'Aydın',
  'Novak',
  'Ricci',
  'Vlachos',
  'Jiménez',
  'Serra',
  'Almeida',
  'Öztürk',
  'Pavlović',
  'De Luca',
  'Galanis',
  'Castillo',
  'Sousa',
];

const pick = (random: () => number, list: readonly string[]): string =>
  list[Math.min(list.length - 1, Math.floor(random() * list.length))]!;

/** One given name, drawn from the list for the age band. */
export function givenName(random: () => number, child: boolean): string {
  return pick(random, child ? CHILD_NAMES : GIVEN_NAMES);
}

export function familyName(random: () => number): string {
  return pick(random, FAMILY_NAMES);
}
